#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Threaded Concept Memory Probe v0.6

Unique Word Node + WordThread Link Table.

This version changes the memory model:

Word is unique.
Thread is an experience.
Word and Thread are connected by many-to-many links.

Activation propagates:

Word
 -> Thread
 -> Word
 -> Thread
 -> Word

A thread becomes stronger when multiple activated words point to the same thread.
This is the core experiment:

"交差する糸が強く震える"

The goal is not document retrieval.
The goal is to verify whether natural associative recall can emerge from
interconnected experience threads.

Meaning is never stored.
Meaning is generated only by the LLM from activated concepts.
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import math
import os
import re
import sqlite3
import sys
import urllib.request
import uuid
from dataclasses import dataclass
from typing import Any, Optional


# This probe does not store sentences as memories.
# It stores unique words and links them to experience threads.
# Meaning, emotion, importance, and relationship interpretation
# must be generated by the LLM at runtime.

# このProbeは文章を記憶として保存しない。
# 単語は一意なノードとして保存し、経験を表すthreadへ多対多で紐づける。
# 重要性・感情・恋人らしさ・意味付けは保存しない。
# それらは現在入力と励起語群を受け取ったLLMが実行時に生成する。


DEFAULT_DB_PATH = "threaded_concept_memory_probe_v0_6.db"
DEFAULT_HALF_LIFE_DAYS = 14.0
DEFAULT_MAX_STRENGTH = 2.0
DEFAULT_REINFORCE_AMOUNT = 0.10
DEFAULT_MAX_DEPTH = 3

DEPTH_DECAY: dict[int, float] = {
    0: 1.00,
    1: 0.40,
    2: 0.15,
    3: 0.05,
    4: 0.02,
}


def enable_localhost_proxy_bypass() -> None:
    bypass_hosts = ["127.0.0.1", "localhost", "::1", "0.0.0.0"]
    existing = os.environ.get("NO_PROXY") or os.environ.get("no_proxy") or ""
    parts = [p.strip() for p in existing.split(",") if p.strip()]
    for host in bypass_hosts:
        if host not in parts:
            parts.append(host)
    value = ",".join(parts)
    os.environ["NO_PROXY"] = value
    os.environ["no_proxy"] = value


def open_url_direct(req: urllib.request.Request, timeout: float):
    opener = urllib.request.build_opener(urllib.request.ProxyHandler({}))
    return opener.open(req, timeout=timeout)


enable_localhost_proxy_bypass()


def normalize_llm_base_url(value: str | None) -> str:
    if not value:
        return ""
    url = value.strip().rstrip("/")
    if not url:
        return ""
    if url.endswith("/chat/completions"):
        url = url[: -len("/chat/completions")]
    if not url.endswith("/v1"):
        url += "/v1"
    return url


@dataclass
class WordNode:
    word_id: str
    word: str
    strength: float
    weight: float
    seen_count: int
    first_seen: str
    last_seen: str


@dataclass
class Thread:
    thread_id: str
    date: str
    source_text: str | None
    words: list[str]


@dataclass
class WordThreadLink:
    word_id: str
    word: str
    thread_id: str
    weight_in_thread: float
    added_at: str


@dataclass
class ExtractedWord:
    word: str
    weight: float


@dataclass
class ActivationTrace:
    from_type: str
    from_id: str
    to_type: str
    to_id: str
    depth: int
    score: float
    reason: str


@dataclass
class ActivatedWord:
    word: str
    score: float
    best_depth: int
    thread_ids: list[str]
    activated_by: list[str]


@dataclass
class ActivatedThread:
    thread_id: str
    score: float
    words: list[str]
    matched_words: list[str]
    activated_by: list[str]
    date: str


@dataclass
class ActivationResult:
    input_words: list[ExtractedWord]
    activated_words: list[ActivatedWord]
    activated_threads: list[ActivatedThread]
    traces: list[ActivationTrace]


class ThreadedConceptMemoryStore:
    def __init__(self, db_path: str = DEFAULT_DB_PATH) -> None:
        self.db_path = db_path
        self.conn = sqlite3.connect(db_path)
        self.conn.row_factory = sqlite3.Row
        self.init_schema()

    def close(self) -> None:
        self.conn.close()

    def init_schema(self) -> None:
        cur = self.conn.cursor()

        cur.execute(
            """
            CREATE TABLE IF NOT EXISTS words (
                word_id TEXT PRIMARY KEY,
                word TEXT UNIQUE NOT NULL,
                strength REAL NOT NULL DEFAULT 1.0,
                weight REAL NOT NULL DEFAULT 1.0,
                seen_count INTEGER NOT NULL DEFAULT 1,
                first_seen TEXT NOT NULL,
                last_seen TEXT NOT NULL
            )
            """
        )

        cur.execute(
            """
            CREATE TABLE IF NOT EXISTS threads (
                thread_id TEXT PRIMARY KEY,
                date TEXT NOT NULL,
                source_text TEXT
            )
            """
        )

        cur.execute(
            """
            CREATE TABLE IF NOT EXISTS word_threads (
                word_id TEXT NOT NULL,
                thread_id TEXT NOT NULL,
                weight_in_thread REAL NOT NULL DEFAULT 1.0,
                added_at TEXT NOT NULL,
                PRIMARY KEY (word_id, thread_id),
                FOREIGN KEY (word_id) REFERENCES words(word_id),
                FOREIGN KEY (thread_id) REFERENCES threads(thread_id)
            )
            """
        )

        cur.execute("CREATE INDEX IF NOT EXISTS idx_words_word ON words(word)")
        cur.execute("CREATE INDEX IF NOT EXISTS idx_word_threads_word ON word_threads(word_id)")
        cur.execute("CREATE INDEX IF NOT EXISTS idx_word_threads_thread ON word_threads(thread_id)")
        self.conn.commit()

    def create_thread(self, words: list[ExtractedWord], source_text: str | None) -> str:
        """
        Create a new experience thread.
        Same word is not inserted again into words.
        Only a new word_threads relation is added.
        """
        now = now_iso()
        date = now[:10]
        thread_id = "thread_" + uuid.uuid4().hex[:12]

        normalized: dict[str, float] = {}
        for item in words:
            word = normalize_word(item.word)
            if not word:
                continue
            weight = clamp(float(item.weight), 0.1, 2.0)
            normalized[word] = max(normalized.get(word, 0.0), weight)

        if "みつき" in normalized:
            # Probe用の最小補正。意味分類ではない。
            # 「みつき」が同一thread内に含まれる場合のみ、thread内重みを少し上げる。
            for w in list(normalized.keys()):
                normalized[w] = clamp(normalized[w] * 1.15, 0.1, 2.3)

        cur = self.conn.cursor()
        cur.execute(
            "INSERT INTO threads(thread_id, date, source_text) VALUES (?, ?, ?)",
            (thread_id, date, source_text),
        )

        for word, weight in normalized.items():
            node = self.get_word_by_text(word)
            if node is None:
                word_id = "word_" + uuid.uuid4().hex[:12]
                cur.execute(
                    """
                    INSERT INTO words(word_id, word, strength, weight, seen_count, first_seen, last_seen)
                    VALUES (?, ?, ?, ?, ?, ?, ?)
                    """,
                    (word_id, word, 1.0, weight, 1, now, now),
                )
            else:
                word_id = node.word_id
                new_seen = node.seen_count + 1
                new_weight = max(node.weight, weight)
                # 同じ単語の再出現は「単語ノード」自体を少し強くする。
                new_strength = min(node.strength + DEFAULT_REINFORCE_AMOUNT, DEFAULT_MAX_STRENGTH)
                cur.execute(
                    """
                    UPDATE words
                    SET strength = ?, weight = ?, seen_count = ?, last_seen = ?
                    WHERE word_id = ?
                    """,
                    (new_strength, new_weight, new_seen, now, word_id),
                )

            cur.execute(
                """
                INSERT OR REPLACE INTO word_threads(word_id, thread_id, weight_in_thread, added_at)
                VALUES (?, ?, ?, ?)
                """,
                (word_id, thread_id, weight, now),
            )

        self.conn.commit()
        return thread_id

    def get_word_by_text(self, word: str) -> Optional[WordNode]:
        row = self.conn.execute(
            """
            SELECT word_id, word, strength, weight, seen_count, first_seen, last_seen
            FROM words
            WHERE word = ?
            """,
            (word,),
        ).fetchone()
        return row_to_word_node(row) if row else None

    def get_word_by_id(self, word_id: str) -> Optional[WordNode]:
        row = self.conn.execute(
            """
            SELECT word_id, word, strength, weight, seen_count, first_seen, last_seen
            FROM words
            WHERE word_id = ?
            """,
            (word_id,),
        ).fetchone()
        return row_to_word_node(row) if row else None

    def get_all_words(self) -> list[str]:
        rows = self.conn.execute("SELECT word FROM words ORDER BY word").fetchall()
        return [r["word"] for r in rows]

    def get_links_for_word(self, word_id: str) -> list[WordThreadLink]:
        rows = self.conn.execute(
            """
            SELECT wt.word_id, w.word, wt.thread_id, wt.weight_in_thread, wt.added_at
            FROM word_threads wt
            JOIN words w ON w.word_id = wt.word_id
            WHERE wt.word_id = ?
            ORDER BY wt.weight_in_thread DESC
            """,
            (word_id,),
        ).fetchall()
        return [row_to_word_thread_link(r) for r in rows]

    def get_links_for_thread(self, thread_id: str) -> list[WordThreadLink]:
        rows = self.conn.execute(
            """
            SELECT wt.word_id, w.word, wt.thread_id, wt.weight_in_thread, wt.added_at
            FROM word_threads wt
            JOIN words w ON w.word_id = wt.word_id
            WHERE wt.thread_id = ?
            ORDER BY wt.weight_in_thread DESC, w.word ASC
            """,
            (thread_id,),
        ).fetchall()
        return [row_to_word_thread_link(r) for r in rows]

    def get_thread(self, thread_id: str) -> Optional[Thread]:
        row = self.conn.execute(
            "SELECT thread_id, date, source_text FROM threads WHERE thread_id = ?",
            (thread_id,),
        ).fetchone()
        if row is None:
            return None
        words = [link.word for link in self.get_links_for_thread(thread_id)]
        return Thread(row["thread_id"], row["date"], row["source_text"], words)

    def list_threads(self, limit: int = 20) -> list[Thread]:
        rows = self.conn.execute(
            """
            SELECT thread_id, date, source_text
            FROM threads
            ORDER BY rowid DESC
            LIMIT ?
            """,
            (limit,),
        ).fetchall()
        return [
            Thread(r["thread_id"], r["date"], r["source_text"], [l.word for l in self.get_links_for_thread(r["thread_id"])])
            for r in rows
        ]

    def list_words(self, limit: int = 100) -> list[WordNode]:
        rows = self.conn.execute(
            """
            SELECT word_id, word, strength, weight, seen_count, first_seen, last_seen
            FROM words
            ORDER BY seen_count DESC, word ASC
            LIMIT ?
            """,
            (limit,),
        ).fetchall()
        return [row_to_word_node(r) for r in rows]

    def reinforce_seen(self, activated_words: list[ActivatedWord]) -> None:
        now = now_iso()
        cur = self.conn.cursor()
        for aw in activated_words:
            node = self.get_word_by_text(aw.word)
            if node is None:
                continue
            # Depthが浅いほど強化。score自体は爆発しうるためlogで抑える。
            gain = DEFAULT_REINFORCE_AMOUNT * (1.0 / (1.0 + aw.best_depth)) * min(math.log1p(aw.score), 1.0)
            cur.execute(
                """
                UPDATE words
                SET strength = ?, seen_count = ?, last_seen = ?
                WHERE word_id = ?
                """,
                (
                    min(node.strength + gain, DEFAULT_MAX_STRENGTH),
                    node.seen_count + 1,
                    now,
                    node.word_id,
                ),
            )
        self.conn.commit()


class WordExtractor:
    def __init__(self, base_url: str = "", api_key: str = "", model: str = "local-model", timeout_sec: float = 12.0) -> None:
        self.base_url = normalize_llm_base_url(base_url or os.getenv("LLM_BASE_URL", ""))
        self.api_key = api_key or os.getenv("LLM_API_KEY", "")
        self.model = model or os.getenv("LLM_MODEL", "local-model")
        self.timeout_sec = timeout_sec

    def extract(self, text: str) -> list[ExtractedWord]:
        if self.base_url:
            try:
                print(f"[llm] extracting words via {self.base_url} model={self.model}", file=sys.stderr)
                return self._extract_with_llm(text)
            except Exception as exc:
                print(f"[warn] LLM word extraction failed, fallback used: {exc}", file=sys.stderr)
        return fallback_extract_words(text)

    def _extract_with_llm(self, text: str) -> list[ExtractedWord]:
        system = (
            "You extract Japanese memory trigger words from a user utterance.\n"
            "Do not classify words. Do not infer relationship labels.\n"
            "Return strict JSON only.\n"
            "Schema: {\"words\":[{\"word\":\"...\",\"weight\":1.0}]}\n"
            "Extract people, objects, actions, places, feelings, time words, and notable nouns/verbs/adjectives.\n"
            "Keep words short. Use base/common forms when natural.\n"
            "Weight range: 0.4 to 1.4. Important concrete words can be 1.2-1.4."
        )
        content = call_openai_compatible_chat(
            base_url=self.base_url,
            api_key=self.api_key,
            model=self.model,
            messages=[
                {"role": "system", "content": system},
                {"role": "user", "content": f"Input:\n{text}\n\nReturn JSON only."},
            ],
            temperature=0.0,
            max_tokens=256,
            timeout_sec=self.timeout_sec,
        )

        data = parse_json_object(content)
        words_raw = data.get("words", [])
        words: list[ExtractedWord] = []
        for item in words_raw:
            if not isinstance(item, dict):
                continue
            word = normalize_word(str(item.get("word", "")))
            if not word:
                continue
            try:
                weight = float(item.get("weight", 1.0))
            except Exception:
                weight = 1.0
            words.append(ExtractedWord(word, clamp(weight, 0.1, 2.0)))
        return dedupe_extracted_words(words) or fallback_extract_words(text)


class ActivationEngine:
    def __init__(self, store: ThreadedConceptMemoryStore, half_life_days: float = DEFAULT_HALF_LIFE_DAYS, max_depth: int = DEFAULT_MAX_DEPTH) -> None:
        self.store = store
        self.half_life_days = half_life_days
        self.max_depth = max_depth

    def activate(self, input_words: list[ExtractedWord], top_words: int = 20, top_threads: int = 8) -> ActivationResult:
        now = now_iso()
        known_words = self.store.get_all_words()

        word_scores: dict[str, float] = {}
        word_best_depth: dict[str, int] = {}
        word_threads: dict[str, set[str]] = {}
        word_activated_by: dict[str, list[str]] = {}

        thread_scores: dict[str, float] = {}
        thread_matched_words: dict[str, set[str]] = {}
        thread_activated_by: dict[str, list[str]] = {}

        traces: list[ActivationTrace] = []

        # Queue: node_type, node_id, score, depth
        queue: list[tuple[str, str, float, int]] = []

        # Use max-score visited, not once-only, because a later intersection may be stronger.
        visited_word_score: dict[str, float] = {}
        visited_thread_score: dict[str, float] = {}

        def record_trace(from_type: str, from_id: str, to_type: str, to_id: str, depth: int, score: float, reason: str) -> None:
            traces.append(ActivationTrace(from_type, from_id, to_type, to_id, depth, score, reason))

        # depth0: input word -> unique Word node.
        for iw in input_words:
            for matched_word, sim in match_known_words(iw.word, known_words):
                node = self.store.get_word_by_text(matched_word)
                if node is None:
                    continue
                score = self._word_score(node, iw.weight * sim, depth=0, now=now)

                add_word_activation(
                    word_scores, word_best_depth, word_threads, word_activated_by,
                    node.word, [], score, 0, f"input:{iw.word}"
                )
                record_trace("input", iw.word, "word", node.word, 0, score, f"matched sim={sim:.2f}")

                if score > visited_word_score.get(node.word_id, 0.0):
                    visited_word_score[node.word_id] = score
                    queue.append(("word", node.word_id, score, 0))

        while queue:
            node_type, node_id, score, depth = queue.pop(0)
            if depth >= self.max_depth:
                continue

            next_depth = depth + 1

            if node_type == "word":
                node = self.store.get_word_by_id(node_id)
                if node is None:
                    continue

                # Word -> all linked Threads.
                for link in self.store.get_links_for_word(node_id):
                    thread_score = score * link.weight_in_thread * DEPTH_DECAY.get(next_depth, 0.03)
                    if thread_score <= 0.001:
                        continue

                    # Important:
                    # If multiple activated words point to the same thread,
                    # the thread score is accumulated.
                    thread_scores[link.thread_id] = thread_scores.get(link.thread_id, 0.0) + thread_score
                    thread_matched_words.setdefault(link.thread_id, set()).add(node.word)
                    add_activated_by(thread_activated_by, link.thread_id, f"word:{node.word}")
                    record_trace("word", node.word, "thread", link.thread_id, next_depth, thread_score, "word->thread")

                    # Continue BFS only when this path is stronger than previous route.
                    if thread_score > visited_thread_score.get(link.thread_id, 0.0):
                        visited_thread_score[link.thread_id] = thread_score
                        queue.append(("thread", link.thread_id, thread_score, next_depth))

            elif node_type == "thread":
                thread_id = node_id

                # Thread -> all linked Words.
                for link in self.store.get_links_for_thread(thread_id):
                    node = self.store.get_word_by_id(link.word_id)
                    if node is None:
                        continue
                    word_score = self._word_score(node, score * link.weight_in_thread, depth=next_depth, now=now)
                    if word_score <= 0.001:
                        continue

                    add_word_activation(
                        word_scores, word_best_depth, word_threads, word_activated_by,
                        node.word, [thread_id], word_score, next_depth, f"thread:{thread_id}"
                    )
                    record_trace("thread", thread_id, "word", node.word, next_depth, word_score, "thread->word")

                    if word_score > visited_word_score.get(node.word_id, 0.0):
                        visited_word_score[node.word_id] = word_score
                        queue.append(("word", node.word_id, word_score, next_depth))

        activated_words = [
            ActivatedWord(
                word=w,
                score=s,
                best_depth=word_best_depth.get(w, 99),
                thread_ids=sorted(word_threads.get(w, set())),
                activated_by=word_activated_by.get(w, [])[:6],
            )
            for w, s in sorted(word_scores.items(), key=lambda kv: kv[1], reverse=True)
            if s > 0.001
        ][:top_words]

        activated_threads: list[ActivatedThread] = []
        for thread_id, score in sorted(thread_scores.items(), key=lambda kv: kv[1], reverse=True)[:top_threads]:
            thread = self.store.get_thread(thread_id)
            if thread is None:
                continue
            activated_threads.append(
                ActivatedThread(
                    thread_id=thread_id,
                    score=score,
                    words=thread.words,
                    matched_words=sorted(thread_matched_words.get(thread_id, set())),
                    activated_by=thread_activated_by.get(thread_id, [])[:8],
                    date=thread.date,
                )
            )

        return ActivationResult(input_words, activated_words, activated_threads, traces)

    def _word_score(self, node: WordNode, activation: float, depth: int, now: str) -> float:
        days = max(days_between_iso(node.last_seen, now), 0.0)
        time_decay = math.exp(-days / self.half_life_days)
        return activation * node.weight * node.strength * DEPTH_DECAY.get(depth, 0.03) * time_decay


class ResponseGenerator:
    def __init__(self, base_url: str = "", api_key: str = "", model: str = "local-model", timeout_sec: float = 12.0) -> None:
        self.base_url = normalize_llm_base_url(base_url or os.getenv("LLM_BASE_URL", ""))
        self.api_key = api_key or os.getenv("LLM_API_KEY", "")
        self.model = model or os.getenv("LLM_MODEL", "local-model")
        self.timeout_sec = timeout_sec

    def generate(self, user_input: str, activation: ActivationResult, include_trace: bool = False, trace_limit: int = 10) -> str:
        prompt = build_response_prompt(user_input, activation, include_trace=include_trace, trace_limit=trace_limit)
        print("[prompt] " + prompt_stats("response_prompt", prompt), file=sys.stderr)

        if self.base_url:
            try:
                print(f"[llm] generating response via {self.base_url} model={self.model}", file=sys.stderr)
                return call_openai_compatible_chat(
                    base_url=self.base_url,
                    api_key=self.api_key,
                    model=self.model,
                    messages=[
                        {
                            "role": "system",
                            "content": (
                                "あなたは日本語で自然に短く返す会話相手です。\n"
                                "Activated Words and Threads are associative memory traces.\n"
                                "They are not exact quoted memories.\n"
                                "Use them as hints for natural recall.\n"
                                "返答は1〜3文。"
                            ),
                        },
                        {"role": "user", "content": prompt},
                    ],
                    temperature=0.7,
                    max_tokens=256,
                    timeout_sec=self.timeout_sec,
                ).strip()
            except Exception as exc:
                print(f"[warn] LLM response generation failed, fallback used: {exc}", file=sys.stderr)
        return fallback_generate_response(user_input, activation)


def build_response_prompt(user_input: str, activation: ActivationResult, include_trace: bool = False, trace_limit: int = 10) -> str:
    lines: list[str] = []
    lines.append("[Current Input]")
    lines.append(user_input)

    lines.append("")
    lines.append("[Extracted Input Words]")
    for w in activation.input_words:
        lines.append(f"- {w.word} ({w.weight:.2f})")

    lines.append("")
    lines.append("[Activated Words]")
    for aw in activation.activated_words:
        by = ", ".join(aw.activated_by[:3])
        threads = ", ".join(aw.thread_ids[:5])
        lines.append(f"- {aw.word} score={aw.score:.3f} depth={aw.best_depth} activated_by={by} threads={threads}")

    lines.append("")
    lines.append("[Activated Threads]")
    for th in activation.activated_threads:
        words = " / ".join(th.words)
        matched = ", ".join(th.matched_words)
        lines.append(f"{th.thread_id} score={th.score:.3f} matched={matched}: {words}")

    if include_trace:
        lines.append("")
        lines.append("[Activation Trace]")
        for tr in activation.traces[:trace_limit]:
            lines.append(f"- d{tr.depth}: {tr.from_type}:{tr.from_id} -> {tr.to_type}:{tr.to_id} score={tr.score:.3f}")
    else:
        lines.append("")
        lines.append("[Activation Trace]")
        lines.append("(omitted from LLM prompt; visible in console log only)")

    lines.append("")
    lines.append("[Instruction]")
    lines.append("励起された単語とthreadは正確な文章記憶ではなく連想の手がかりである。")
    lines.append("複数の入力語が同じthreadを指している場合、そのthreadをより強い手がかりとして扱う。")
    lines.append("断定しすぎず、自然な想起として短く返す。")
    return "\n".join(lines)


def print_activation(result: ActivationResult, trace_limit: int = 80) -> None:
    print("\n[Input Words]")
    for w in result.input_words:
        print(f"- {w.word} weight={w.weight:.2f}")

    print("\n[Activated Words]")
    for aw in result.activated_words:
        tids = ", ".join(aw.thread_ids[:5])
        by = ", ".join(aw.activated_by[:4]) if aw.activated_by else "-"
        print(f"- {aw.word} score={aw.score:.4f} depth={aw.best_depth} activated_by={by} threads={tids}")

    print("\n[Activated Threads]")
    for th in result.activated_threads:
        matched = ", ".join(th.matched_words) if th.matched_words else "-"
        by = ", ".join(th.activated_by[:4]) if th.activated_by else "-"
        print(f"- {th.thread_id} score={th.score:.4f} matched={matched} activated_by={by} date={th.date}: {' / '.join(th.words)}")

    print("\n[Activation Trace]")
    if not result.traces:
        print("- (no trace)")
    for tr in result.traces[:trace_limit]:
        print(f"- d{tr.depth}: {tr.from_type}:{tr.from_id} -> {tr.to_type}:{tr.to_id} score={tr.score:.4f} reason={tr.reason}")


def call_openai_compatible_chat(
    base_url: str,
    api_key: str,
    model: str,
    messages: list[dict[str, str]],
    temperature: float,
    max_tokens: int,
    timeout_sec: float,
) -> str:
    url = normalize_llm_base_url(base_url) + "/chat/completions"
    payload = {
        "model": model,
        "messages": messages,
        "temperature": temperature,
        "max_tokens": max_tokens,
        "stream": False,
    }
    headers = {"Content-Type": "application/json"}
    if api_key:
        headers["Authorization"] = f"Bearer {api_key}"

    req = urllib.request.Request(
        url=url,
        data=json.dumps(payload, ensure_ascii=False).encode("utf-8"),
        headers=headers,
        method="POST",
    )

    with open_url_direct(req, timeout=timeout_sec) as resp:
        raw = resp.read().decode("utf-8")

    data = json.loads(raw)
    return data["choices"][0]["message"]["content"]


def check_openai_compatible_health(base_url: str, timeout_sec: float = 3.0) -> tuple[bool, str]:
    base_url = normalize_llm_base_url(base_url)
    if not base_url:
        return False, "base_url is empty"

    root = base_url[:-3] if base_url.endswith("/v1") else base_url
    candidates = [root + "/health", base_url + "/models"]
    last_error = ""
    for url in candidates:
        try:
            req = urllib.request.Request(url=url, method="GET")
            with open_url_direct(req, timeout=timeout_sec) as resp:
                body = resp.read(200).decode("utf-8", errors="replace")
                return True, f"GET {url} -> HTTP {getattr(resp, 'status', 200)} {body[:120]}"
        except Exception as exc:
            last_error = f"GET {url} failed: {exc}"
    return False, last_error


def parse_json_object(text: str) -> dict[str, Any]:
    text = text.strip()
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass
    match = re.search(r"\{.*\}", text, flags=re.DOTALL)
    if not match:
        raise ValueError("No JSON object found in LLM output.")
    return json.loads(match.group(0))


def fallback_extract_words(text: str) -> list[ExtractedWord]:
    text = normalize_text(text)
    protected_terms = [
        "みつき", "のりこ", "チーズケーキ", "コーヒー", "紅茶", "好き",
        "カフェ", "帰り", "食べる", "映画", "ポップコーン",
        "カッターナイフ", "カッター", "怪我", "苦手", "昔",
        "誕生日", "猫", "ソラ", "ギター",
    ]

    found: list[ExtractedWord] = []
    for term in protected_terms:
        if term in text:
            found.append(ExtractedWord(term, 1.2 if len(term) >= 4 else 1.0))

    if "ケーキ" in text and "チーズケーキ" not in [w.word for w in found]:
        found.append(ExtractedWord("ケーキ", 1.0))
    if "カッター" in text and "カッターナイフ" not in [w.word for w in found]:
        found.append(ExtractedWord("カッターナイフ", 0.9))

    chunks = re.findall(r"[A-Za-z0-9]+|[ぁ-んァ-ン一-龥ー]{2,}", text)
    stop = {"です", "ます", "だった", "って", "これ", "それ", "今日", "明日", "昨日", "する", "した", "ある", "いる", "もの", "なもの"}
    for ch in chunks:
        ch = normalize_word(ch)
        if not ch or ch in stop:
            continue
        if len(ch) >= 8 and re.search(r"[はがをにへでとてもやの]", ch):
            continue
        if any(ch in term and ch != term for term in protected_terms):
            continue
        found.append(ExtractedWord(ch, 0.8))

    return dedupe_extracted_words(found)


def dedupe_extracted_words(words: list[ExtractedWord]) -> list[ExtractedWord]:
    d: dict[str, float] = {}
    for item in words:
        word = normalize_word(item.word)
        if not word:
            continue
        d[word] = max(d.get(word, 0.0), clamp(item.weight, 0.1, 2.0))
    return [ExtractedWord(w, weight) for w, weight in sorted(d.items(), key=lambda kv: kv[1], reverse=True)]


def match_known_words(input_word: str, known_words: list[str]) -> list[tuple[str, float]]:
    input_word = normalize_word(input_word)
    if not input_word:
        return []

    result: list[tuple[str, float]] = []
    for known in known_words:
        if input_word == known:
            result.append((known, 1.0))
        elif input_word in known or known in input_word:
            short_len = max(min(len(input_word), len(known)), 1)
            long_len = max(max(len(input_word), len(known)), 1)
            sim = 0.72 + 0.20 * (short_len / long_len)
            result.append((known, clamp(sim, 0.55, 0.92)))
        elif loose_katakana_match(input_word, known):
            result.append((known, 0.72))

    result.sort(key=lambda x: x[1], reverse=True)
    return result[:12]


def loose_katakana_match(a: str, b: str) -> bool:
    a2 = a.replace("ー", "")
    b2 = b.replace("ー", "")
    return len(a2) >= 3 and len(b2) >= 3 and (a2 in b2 or b2 in a2)


def fallback_generate_response(user_input: str, activation: ActivationResult) -> str:
    top = [w.word for w in activation.activated_words[:6]]
    if not top:
        return "まだうまく思い出せないけど、その話もう少し聞かせて。"
    if "チーズケーキ" in top and "コーヒー" in top:
        return "チーズケーキとコーヒーが強く出てきてるよ。みつきの好きなものとして、その二つがつながってる感じがする。"
    if "チーズケーキ" in top:
        return "チーズケーキが出てきたよ。みつきが好きって話とつながってる気がする。"
    if "カッターナイフ" in top or "カッター" in top:
        return "カッターや怪我、苦手って単語が反応してる。少し気をつけた方がよさそう。"
    return "今反応してるのは、" + "、".join(top[:4]) + " あたりかな。"


def add_activated_by(target: dict[str, list[str]], key: str, value: str) -> None:
    target.setdefault(key, [])
    if value not in target[key]:
        target[key].append(value)


def add_word_activation(
    word_scores: dict[str, float],
    word_best_depth: dict[str, int],
    word_threads: dict[str, set[str]],
    word_activated_by: dict[str, list[str]],
    word: str,
    thread_ids: list[str],
    score: float,
    depth: int,
    activated_by: str,
) -> None:
    word_scores[word] = word_scores.get(word, 0.0) + score
    word_best_depth[word] = min(word_best_depth.get(word, 99), depth)
    word_threads.setdefault(word, set()).update(thread_ids)
    add_activated_by(word_activated_by, word, activated_by)


def estimate_prompt_tokens_rough(text: str) -> int:
    ascii_chars = sum(1 for c in text if ord(c) < 128)
    non_ascii_chars = len(text) - ascii_chars
    return int((ascii_chars / 4.0) + (non_ascii_chars / 1.6))


def prompt_stats(label: str, text: str) -> str:
    return f"{label}: chars={len(text)}, lines={text.count(chr(10)) + 1 if text else 0}, rough_tokens={estimate_prompt_tokens_rough(text)}"


def normalize_text(text: str) -> str:
    return text.strip().replace("　", " ")


def normalize_word(word: str) -> str:
    word = normalize_text(word)
    return word.strip(" \t\r\n。、,.!?！？「」『』（）()[]【】")


def clamp(v: float, lo: float, hi: float) -> float:
    return max(lo, min(hi, v))


def now_iso() -> str:
    return dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds")


def days_between_iso(start: str, end: str) -> float:
    try:
        s = dt.datetime.fromisoformat(start)
        e = dt.datetime.fromisoformat(end)
        return max((e - s).total_seconds() / 86400.0, 0.0)
    except Exception:
        return 0.0


def row_to_word_node(row: sqlite3.Row) -> WordNode:
    return WordNode(
        word_id=row["word_id"],
        word=row["word"],
        strength=float(row["strength"]),
        weight=float(row["weight"]),
        seen_count=int(row["seen_count"]),
        first_seen=row["first_seen"],
        last_seen=row["last_seen"],
    )


def row_to_word_thread_link(row: sqlite3.Row) -> WordThreadLink:
    return WordThreadLink(
        word_id=row["word_id"],
        word=row["word"],
        thread_id=row["thread_id"],
        weight_in_thread=float(row["weight_in_thread"]),
        added_at=row["added_at"],
    )


def build_components(args: argparse.Namespace) -> tuple[ThreadedConceptMemoryStore, WordExtractor, ActivationEngine, ResponseGenerator]:
    store = ThreadedConceptMemoryStore(args.db)
    extractor = WordExtractor(args.base_url, args.api_key, args.model, args.timeout)
    engine = ActivationEngine(store, args.half_life_days, args.max_depth)
    generator = ResponseGenerator(args.base_url, args.api_key, args.model, args.timeout)
    return store, extractor, engine, generator


def cmd_add(args: argparse.Namespace) -> int:
    store, extractor, _, _ = build_components(args)
    try:
        words = extractor.extract(args.text)
        thread_id = store.create_thread(words, source_text=args.text)
        print(f"saved: {thread_id}")
        print("words:", " / ".join(f"{w.word}({w.weight:.2f})" for w in words))
        return 0
    finally:
        store.close()


def cmd_ask(args: argparse.Namespace) -> int:
    store, extractor, engine, generator = build_components(args)
    try:
        words = extractor.extract(args.text)
        result = engine.activate(words, args.top_words, args.top_threads)
        print_activation(result, trace_limit=args.trace_limit)
        if not args.no_reinforce:
            store.reinforce_seen(result.activated_words)
        if not args.no_response:
            print("\n[Response]")
            print(generator.generate(args.text, result, args.response_include_trace, args.response_trace_limit))
        return 0
    finally:
        store.close()


def cmd_threads(args: argparse.Namespace) -> int:
    store = ThreadedConceptMemoryStore(args.db)
    try:
        for th in store.list_threads(args.limit):
            print(f"{th.thread_id} {th.date}: {' / '.join(th.words)}")
            if args.show_source:
                print(f"  source(debug only): {th.source_text}")
        return 0
    finally:
        store.close()


def cmd_words(args: argparse.Namespace) -> int:
    store = ThreadedConceptMemoryStore(args.db)
    try:
        for node in store.list_words(args.limit):
            links = store.get_links_for_word(node.word_id)
            tids = ", ".join(l.thread_id for l in links[:8])
            print(f"{node.word} seen={node.seen_count} strength={node.strength:.2f} weight={node.weight:.2f} threads={tids}")
        return 0
    finally:
        store.close()


def cmd_seed_tests(args: argparse.Namespace) -> int:
    store, extractor, engine, generator = build_components(args)
    try:
        seeds = [
            "みつきはチーズケーキが好き",
            "みつきはコーヒーが好き",
            "のりこは紅茶が好き",
            "帰りにカフェでチーズケーキを食べたい",
            "映画を見るときはポップコーンがほしい",
            "ポップコーンを食べながらカフェで休みたい",
            "昔カッターナイフで怪我をした",
            "カッターナイフは少し苦手",
        ]

        for s in seeds:
            words = extractor.extract(s)
            thread_id = store.create_thread(words, source_text=s)
            print(f"seed saved: {thread_id}: {s}")
            print("  words:", " / ".join(w.word for w in words))

        tests = [
            "みつきの好きなものは？",
            "カフェ行きたい",
            "映画楽しみ",
            "カッター使う作業がある",
        ]

        for t in tests:
            print("\n" + "=" * 60)
            print("[Test Input]", t)
            words = extractor.extract(t)
            result = engine.activate(words, args.top_words, args.top_threads)
            print_activation(result, trace_limit=args.trace_limit)
            if args.seed_generate_response:
                print("\n[Response]")
                print(generator.generate(t, result, args.response_include_trace, args.response_trace_limit))
            else:
                print("\n[Response]")
                print("(skipped; use --seed-generate-response to test LLM response generation)")
        return 0
    finally:
        store.close()


def cmd_chat(args: argparse.Namespace) -> int:
    store, extractor, engine, generator = build_components(args)
    try:
        print("Threaded Concept Memory Probe v0.6")
        print(f"LLM: {'enabled ' + normalize_llm_base_url(args.base_url) if normalize_llm_base_url(args.base_url) else 'disabled; fallback mode'}")
        print("HTTP proxy: bypassed for local/direct calls")
        print("Commands: /exit, /threads, /words, /add <text>, /ask <text>")
        print("Default: input is treated as /ask, then stored as a new thread.")
        while True:
            try:
                text = input("\n> ").strip()
            except EOFError:
                print()
                break

            if not text:
                continue
            if text in {"/exit", "exit", "quit", "/quit"}:
                break
            if text == "/threads":
                for th in store.list_threads(20):
                    print(f"{th.thread_id} {th.date}: {' / '.join(th.words)}")
                continue
            if text == "/words":
                for node in store.list_words(50):
                    links = store.get_links_for_word(node.word_id)
                    print(f"{node.word} seen={node.seen_count} threads={len(links)}")
                continue

            mode = "ask_then_add"
            if text.startswith("/add "):
                mode = "add"
                text = text[5:].strip()
            elif text.startswith("/ask "):
                mode = "ask"
                text = text[5:].strip()

            words = extractor.extract(text)

            if mode in {"ask", "ask_then_add"}:
                result = engine.activate(words, args.top_words, args.top_threads)
                print_activation(result, trace_limit=args.trace_limit)
                store.reinforce_seen(result.activated_words)
                print("\n[Response]")
                print(generator.generate(text, result, args.response_include_trace, args.response_trace_limit))

            if mode in {"add", "ask_then_add"}:
                thread_id = store.create_thread(words, source_text=text)
                print(f"\n[saved] {thread_id}: " + " / ".join(w.word for w in words))

        return 0
    finally:
        store.close()


def cmd_config(args: argparse.Namespace) -> int:
    base_url = normalize_llm_base_url(args.base_url or args.chat_base_url or os.getenv("LLM_BASE_URL", ""))
    print("[LLM Config]")
    print(f"base_url: {base_url or '(not set; fallback mode)'}")
    print(f"model: {args.model}")
    print(f"api_key: {'set' if (args.api_key or os.getenv('LLM_API_KEY')) else '(not set)'}")
    print(f"NO_PROXY: {os.environ.get('NO_PROXY', '')}")
    print("proxy_mode: disabled for this script's HTTP calls")
    if not base_url:
        return 0
    ok, detail = check_openai_compatible_health(base_url, timeout_sec=min(args.timeout, 5.0))
    print("health:", "ok" if ok else "failed")
    print("detail:", detail)
    if args.generate_test:
        try:
            content = call_openai_compatible_chat(
                base_url=base_url,
                api_key=args.api_key,
                model=args.model,
                messages=[
                    {"role": "system", "content": "Return only JSON. No explanation."},
                    {"role": "user", "content": "{\"ok\":true}"},
                ],
                temperature=0.0,
                max_tokens=16,
                timeout_sec=args.timeout,
            )
            print("generation: ok")
            print("sample:", content.strip()[:200])
        except Exception as exc:
            print("generation: failed")
            print("error:", exc)
    return 0


def cmd_prompt_preview(args: argparse.Namespace) -> int:
    store, extractor, engine, _ = build_components(args)
    try:
        words = extractor.extract(args.text)
        result = engine.activate(words, args.top_words, args.top_threads)
        prompt_without_trace = build_response_prompt(args.text, result, include_trace=False)
        prompt_with_trace = build_response_prompt(args.text, result, include_trace=True, trace_limit=args.response_trace_limit)
        print_activation(result, trace_limit=args.trace_limit)
        print("\n[Prompt Size]")
        print(prompt_stats("without_trace", prompt_without_trace))
        print(prompt_stats(f"with_trace_limit_{args.response_trace_limit}", prompt_with_trace))
        if args.show_prompt:
            print("\n[Prompt Without Trace]")
            print(prompt_without_trace)
            print("\n[Prompt With Trace]")
            print(prompt_with_trace)
        return 0
    finally:
        store.close()


def make_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Threaded Concept Memory Probe v0.6")
    parser.add_argument("--db", default=DEFAULT_DB_PATH)
    parser.add_argument("--base-url", default=os.getenv("LLM_BASE_URL", ""))
    parser.add_argument("--chat-base-url", default="")
    parser.add_argument("--api-key", default=os.getenv("LLM_API_KEY", ""))
    parser.add_argument("--model", default=os.getenv("LLM_MODEL", "local-model"))
    parser.add_argument("--timeout", type=float, default=12.0)
    parser.add_argument("--half-life-days", type=float, default=DEFAULT_HALF_LIFE_DAYS)
    parser.add_argument("--max-depth", type=int, default=DEFAULT_MAX_DEPTH)
    parser.add_argument("--top-words", type=int, default=20)
    parser.add_argument("--top-threads", type=int, default=8)
    parser.add_argument("--trace-limit", type=int, default=80)
    parser.add_argument("--response-include-trace", action="store_true")
    parser.add_argument("--response-trace-limit", type=int, default=10)

    sub = parser.add_subparsers(dest="command", required=True)

    p_add = sub.add_parser("add")
    p_add.add_argument("text")
    p_add.set_defaults(func=cmd_add)

    p_ask = sub.add_parser("ask")
    p_ask.add_argument("text")
    p_ask.add_argument("--no-response", action="store_true")
    p_ask.add_argument("--no-reinforce", action="store_true")
    p_ask.set_defaults(func=cmd_ask)

    p_threads = sub.add_parser("threads")
    p_threads.add_argument("--limit", type=int, default=20)
    p_threads.add_argument("--show-source", action="store_true")
    p_threads.set_defaults(func=cmd_threads)

    p_words = sub.add_parser("words")
    p_words.add_argument("--limit", type=int, default=100)
    p_words.set_defaults(func=cmd_words)

    p_seed = sub.add_parser("seed-tests")
    p_seed.add_argument("--seed-generate-response", action="store_true")
    p_seed.set_defaults(func=cmd_seed_tests)

    p_chat = sub.add_parser("chat")
    p_chat.set_defaults(func=cmd_chat)

    p_config = sub.add_parser("config")
    p_config.add_argument("--generate-test", action="store_true")
    p_config.set_defaults(func=cmd_config)

    p_preview = sub.add_parser("prompt-preview")
    p_preview.add_argument("text")
    p_preview.add_argument("--show-prompt", action="store_true")
    p_preview.set_defaults(func=cmd_prompt_preview)

    return parser


def main(argv: Optional[list[str]] = None) -> int:
    parser = make_parser()
    args = parser.parse_args(argv)

    if getattr(args, "chat_base_url", ""):
        args.base_url = args.chat_base_url
    args.base_url = normalize_llm_base_url(args.base_url)

    return int(args.func(args))


if __name__ == "__main__":
    raise SystemExit(main())
