#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Threaded Concept Memory Probe v0.4

This version introduces multi-hop activation.

Words are treated as primary memory nodes.

Threads are treated as traces of experiences connecting words.

Activation propagates:

Word
 -> Thread
 -> Word
 -> Thread
 -> Word

The goal is not document retrieval.

The goal is to verify whether natural associative recall can emerge from interconnected experience threads.

Meaning is never stored.

Meaning is generated only by the LLM from the activated concepts.

Usage examples:

  python threaded_concept_memory_probe_v0_4.py --base-url http://127.0.0.1:8080 --model local-model config
  python threaded_concept_memory_probe_v0_4.py --base-url http://127.0.0.1:8080 --model local-model seed-tests
  python threaded_concept_memory_probe_v0_4.py --base-url http://127.0.0.1:8080 --model local-model chat
"""

from __future__ import annotations

import argparse
import dataclasses
import datetime as dt
import json
import math
import os
import re
import sqlite3
import sys
import time
import urllib.error
import urllib.request
import uuid
from dataclasses import dataclass
from typing import Any, Iterable, Optional


# This probe does not store sentences as memories.
# It stores words as traces on experience threads.
# Meaning, emotion, importance, and relationship interpretation
# must be generated by the LLM at runtime.

# このProbeは文章を記憶として保存しない。
# 会話から抽出された単語を、経験を表すthread上の痕跡として保存する。
# 重要性・感情・恋人らしさ・意味付けは保存しない。
# それらは現在入力と励起語群を受け取ったLLMが実行時に生成する。


DEFAULT_DB_PATH = "threaded_concept_memory_probe.db"


def enable_localhost_proxy_bypass() -> None:
    """
    Force localhost / LAN-style local endpoints to bypass HTTP proxy settings.

    Some Windows environments have HTTP_PROXY / HTTPS_PROXY configured.
    urllib.request.urlopen may then try to send http://127.0.0.1:8080 through
    that proxy, which breaks local llama.cpp / proxy servers.

    This probe should always connect directly to localhost.
    """
    bypass_hosts = [
        "127.0.0.1",
        "localhost",
        "::1",
        "0.0.0.0",
    ]

    existing = os.environ.get("NO_PROXY") or os.environ.get("no_proxy") or ""
    parts = [p.strip() for p in existing.split(",") if p.strip()]
    for host in bypass_hosts:
        if host not in parts:
            parts.append(host)

    value = ",".join(parts)
    os.environ["NO_PROXY"] = value
    os.environ["no_proxy"] = value


def open_url_direct(req: urllib.request.Request, timeout: float):
    """
    Open URL without using environment proxy settings.
    """
    opener = urllib.request.build_opener(urllib.request.ProxyHandler({}))
    return opener.open(req, timeout=timeout)


enable_localhost_proxy_bypass()

DEFAULT_HALF_LIFE_DAYS = 14.0
DEFAULT_MAX_STRENGTH = 2.0
DEFAULT_REINFORCE_AMOUNT = 0.18
DEFAULT_MAX_DEPTH = 3


def normalize_llm_base_url(value: str | None) -> str:
    """
    Accept both:
      http://127.0.0.1:8080
      http://127.0.0.1:8080/v1

    Internally this script calls:
      {base_url}/chat/completions
    so the normalized base URL must end with /v1.
    """
    if not value:
        return ""
    url = value.strip().rstrip("/")
    if not url:
        return ""
    if url.endswith("/chat/completions"):
        url = url[: -len("/chat/completions")]
    if not url.endswith("/v1"):
        url += "/v1"
    return url


DEPTH_DECAY: dict[int, float] = {
    0: 1.00,
    1: 0.40,
    2: 0.15,
    3: 0.05,
}


@dataclass
class WordMemory:
    word: str
    thread_id: str
    date: str
    strength: float
    weight: float
    last_seen: str
    seen_count: int


@dataclass
class Thread:
    thread_id: str
    date: str
    source_text: str | None
    words: list[str]


@dataclass
class ExtractedWord:
    word: str
    weight: float


@dataclass
class ActivationTrace:
    from_type: str
    from_id: str
    to_type: str
    to_id: str
    depth: int
    score: float
    reason: str


@dataclass
class ActivatedWord:
    word: str
    score: float
    best_depth: int
    thread_ids: list[str]
    reasons: list[str]
    activated_by: list[str]


@dataclass
class ActivatedThread:
    thread_id: str
    score: float
    words: list[str]
    date: str
    activated_by: list[str]


@dataclass
class ActivationResult:
    input_words: list[ExtractedWord]
    activated_words: list[ActivatedWord]
    activated_threads: list[ActivatedThread]
    traces: list[ActivationTrace]


class ThreadedConceptMemoryStore:
    def __init__(self, db_path: str = DEFAULT_DB_PATH) -> None:
        self.db_path = db_path
        self.conn = sqlite3.connect(db_path)
        self.conn.row_factory = sqlite3.Row
        self.init_schema()

    def close(self) -> None:
        self.conn.close()

    def init_schema(self) -> None:
        cur = self.conn.cursor()

        cur.execute(
            """
            CREATE TABLE IF NOT EXISTS threads (
                thread_id TEXT PRIMARY KEY,
                date TEXT NOT NULL,
                source_text TEXT
            )
            """
        )

        cur.execute(
            """
            CREATE TABLE IF NOT EXISTS word_memories (
                word TEXT NOT NULL,
                thread_id TEXT NOT NULL,
                date TEXT NOT NULL,
                strength REAL NOT NULL,
                weight REAL NOT NULL,
                last_seen TEXT NOT NULL,
                seen_count INTEGER NOT NULL,
                PRIMARY KEY (word, thread_id),
                FOREIGN KEY (thread_id) REFERENCES threads(thread_id)
            )
            """
        )

        cur.execute(
            "CREATE INDEX IF NOT EXISTS idx_word_memories_word ON word_memories(word)"
        )
        cur.execute(
            "CREATE INDEX IF NOT EXISTS idx_word_memories_thread ON word_memories(thread_id)"
        )
        self.conn.commit()

    def create_thread(self, words: list[ExtractedWord], source_text: str | None) -> str:
        now = now_iso()
        date = now[:10]
        thread_id = "thread_" + uuid.uuid4().hex[:12]

        normalized: dict[str, float] = {}
        for item in words:
            word = normalize_word(item.word)
            if not word:
                continue
            weight = clamp(float(item.weight), 0.1, 2.0)
            if word in normalized:
                normalized[word] = max(normalized[word], weight)
            else:
                normalized[word] = weight

        cur = self.conn.cursor()
        cur.execute(
            "INSERT INTO threads(thread_id, date, source_text) VALUES (?, ?, ?)",
            (thread_id, date, source_text),
        )

        for word, weight in normalized.items():
            if "みつき" in normalized:
                # Probe用の最小補正。
                # 「みつき」が同じ発話内に含まれる場合のみ、ユーザー関連らしさとして少し重くする。
                weight *= 1.2
            cur.execute(
                """
                INSERT INTO word_memories(word, thread_id, date, strength, weight, last_seen, seen_count)
                VALUES (?, ?, ?, ?, ?, ?, ?)
                """,
                (word, thread_id, date, clamp(weight, 0.1, 2.4), clamp(weight, 0.1, 2.4), now, 1),
            )

        self.conn.commit()
        return thread_id

    def get_memories_by_word(self, word: str) -> list[WordMemory]:
        cur = self.conn.cursor()
        rows = cur.execute(
            """
            SELECT word, thread_id, date, strength, weight, last_seen, seen_count
            FROM word_memories
            WHERE word = ?
            """,
            (word,),
        ).fetchall()
        return [row_to_word_memory(r) for r in rows]

    def get_all_words(self) -> list[str]:
        rows = self.conn.execute(
            "SELECT DISTINCT word FROM word_memories ORDER BY word"
        ).fetchall()
        return [r["word"] for r in rows]

    def get_thread_words(self, thread_id: str) -> list[WordMemory]:
        rows = self.conn.execute(
            """
            SELECT word, thread_id, date, strength, weight, last_seen, seen_count
            FROM word_memories
            WHERE thread_id = ?
            ORDER BY weight DESC, word ASC
            """,
            (thread_id,),
        ).fetchall()
        return [row_to_word_memory(r) for r in rows]

    def get_threads_for_word(self, word: str) -> list[str]:
        rows = self.conn.execute(
            "SELECT thread_id FROM word_memories WHERE word = ?",
            (word,),
        ).fetchall()
        return [r["thread_id"] for r in rows]

    def get_thread(self, thread_id: str) -> Optional[Thread]:
        row = self.conn.execute(
            "SELECT thread_id, date, source_text FROM threads WHERE thread_id = ?",
            (thread_id,),
        ).fetchone()
        if row is None:
            return None
        words = [m.word for m in self.get_thread_words(thread_id)]
        return Thread(
            thread_id=row["thread_id"],
            date=row["date"],
            source_text=row["source_text"],
            words=words,
        )

    def reinforce_seen(
        self,
        activated_words: Iterable[ActivatedWord],
        reinforce_amount: float = DEFAULT_REINFORCE_AMOUNT,
        max_strength: float = DEFAULT_MAX_STRENGTH,
    ) -> None:
        now = now_iso()
        cur = self.conn.cursor()

        for aw in activated_words:
            for thread_id in aw.thread_ids:
                row = cur.execute(
                    """
                    SELECT strength, last_seen, seen_count
                    FROM word_memories
                    WHERE word = ? AND thread_id = ?
                    """,
                    (aw.word, thread_id),
                ).fetchone()
                if row is None:
                    continue

                days = days_between_iso(row["last_seen"], now)
                recency_bonus = 1.0 + math.exp(-days / 3.0)
                depth_penalty = DEPTH_DECAY.get(aw.best_depth, 0.05)
                increment = reinforce_amount * recency_bonus * depth_penalty
                new_strength = min(float(row["strength"]) + increment, max_strength)

                cur.execute(
                    """
                    UPDATE word_memories
                    SET strength = ?, last_seen = ?, seen_count = ?
                    WHERE word = ? AND thread_id = ?
                    """,
                    (
                        new_strength,
                        now,
                        int(row["seen_count"]) + 1,
                        aw.word,
                        thread_id,
                    ),
                )

        self.conn.commit()

    def list_threads(self, limit: int = 20) -> list[Thread]:
        rows = self.conn.execute(
            """
            SELECT thread_id, date, source_text
            FROM threads
            ORDER BY rowid DESC
            LIMIT ?
            """,
            (limit,),
        ).fetchall()
        result: list[Thread] = []
        for row in rows:
            result.append(
                Thread(
                    thread_id=row["thread_id"],
                    date=row["date"],
                    source_text=row["source_text"],
                    words=[m.word for m in self.get_thread_words(row["thread_id"])],
                )
            )
        return result


class WordExtractor:
    def __init__(
        self,
        base_url: str | None = None,
        api_key: str | None = None,
        model: str | None = None,
        timeout_sec: float = 30.0,
    ) -> None:
        self.base_url = normalize_llm_base_url(base_url or os.getenv("LLM_BASE_URL") or "")
        self.api_key = api_key or os.getenv("LLM_API_KEY") or ""
        self.model = model or os.getenv("LLM_MODEL") or "local-model"
        self.timeout_sec = timeout_sec

    def extract(self, text: str) -> list[ExtractedWord]:
        if self.base_url:
            try:
                print(f"[llm] extracting words via {self.base_url} model={self.model}", file=sys.stderr)
                return self._extract_with_llm(text)
            except Exception as exc:
                print(f"[warn] LLM word extraction failed, fallback used: {exc}", file=sys.stderr)
        return fallback_extract_words(text)

    def _extract_with_llm(self, text: str) -> list[ExtractedWord]:
        system = (
            "You extract Japanese memory trigger words from a user utterance.\n"
            "Do not classify words. Do not infer relationship labels.\n"
            "Return strict JSON only.\n"
            "Schema: {\"words\":[{\"word\":\"...\",\"weight\":1.0}]}\n"
            "Extract people, objects, actions, places, feelings, time words, and notable nouns/verbs/adjectives.\n"
            "Keep words short. Use base/common forms when natural.\n"
            "Weight range: 0.4 to 1.4. Important concrete words can be 1.2-1.4."
        )
        user = f"Input:\n{text}\n\nReturn JSON only."

        content = call_openai_compatible_chat(
            base_url=self.base_url,
            api_key=self.api_key,
            model=self.model,
            messages=[
                {"role": "system", "content": system},
                {"role": "user", "content": user},
            ],
            temperature=0.0,
            max_tokens=512,
            timeout_sec=self.timeout_sec,
        )

        data = parse_json_object(content)
        words_raw = data.get("words", [])
        words: list[ExtractedWord] = []
        for item in words_raw:
            if not isinstance(item, dict):
                continue
            word = normalize_word(str(item.get("word", "")))
            if not word:
                continue
            try:
                weight = float(item.get("weight", 1.0))
            except Exception:
                weight = 1.0
            words.append(ExtractedWord(word=word, weight=clamp(weight, 0.1, 2.0)))

        if not words:
            return fallback_extract_words(text)
        return dedupe_extracted_words(words)


class ActivationEngine:
    def __init__(
        self,
        store: ThreadedConceptMemoryStore,
        half_life_days: float = DEFAULT_HALF_LIFE_DAYS,
        max_depth: int = DEFAULT_MAX_DEPTH,
    ) -> None:
        self.store = store
        self.half_life_days = half_life_days
        self.max_depth = max_depth

    def activate(self, input_words: list[ExtractedWord], top_words: int = 20, top_threads: int = 8) -> ActivationResult:
        """
        v0.4 multi-hop BFS activation.

        Node types:
          word:<word>
          thread:<thread_id>

        Propagation:
          input word -> matching memory word          depth 0
          word       -> threads containing the word   depth 1
          thread     -> words inside the thread       depth 2
          word       -> other threads sharing word     depth 3
          thread     -> words inside that thread       depth 4 if max_depth allows

        The CLI default max_depth is 3, matching the v0.4 instruction.
        With max_depth=3, the key chain is:
          Word -> Thread -> Word -> Thread
        and ActivatedThreads reveal the next experience reached.
        If you want the final words inside the reached thread too, run --max-depth 4.
        """
        now = now_iso()
        known_words = self.store.get_all_words()

        word_scores: dict[str, float] = {}
        word_best_depth: dict[str, int] = {}
        word_threads: dict[str, set[str]] = {}
        word_reasons: dict[str, list[str]] = {}
        word_activated_by: dict[str, list[str]] = {}

        thread_scores: dict[str, float] = {}
        thread_activated_by: dict[str, list[str]] = {}

        traces: list[ActivationTrace] = []

        # Queue item:
        #   node_type, node_id, activation, depth, activated_by
        queue: list[tuple[str, str, float, int, str]] = []

        visited_word: dict[str, float] = {}
        visited_thread: dict[str, float] = {}

        def record_trace(from_type: str, from_id: str, to_type: str, to_id: str, depth: int, score: float, reason: str) -> None:
            traces.append(
                ActivationTrace(
                    from_type=from_type,
                    from_id=from_id,
                    to_type=to_type,
                    to_id=to_id,
                    depth=depth,
                    score=score,
                    reason=reason,
                )
            )

        # depth0: input words excite matching stored words.
        for iw in input_words:
            candidates = match_known_words(iw.word, known_words)
            for matched_word, sim in candidates:
                memories = self.store.get_memories_by_word(matched_word)
                for mem in memories:
                    input_activation = iw.weight * sim
                    score = self._memory_score(mem, input_activation, depth=0, now=now)

                    add_word_activation_v04(
                        word_scores, word_best_depth, word_threads, word_reasons, word_activated_by,
                        mem.word, mem.thread_id, score, 0, f"direct:{iw.word}", f"input:{iw.word}"
                    )
                    record_trace("input", iw.word, "word", mem.word, 0, score, f"matched sim={sim:.2f}")

                    if score > visited_word.get(mem.word, 0.0):
                        visited_word[mem.word] = score
                        queue.append(("word", mem.word, score, 0, f"input:{iw.word}"))

        while queue:
            node_type, node_id, activation, depth, activated_by = queue.pop(0)
            if depth >= self.max_depth:
                continue

            next_depth = depth + 1

            if node_type == "word":
                # Word -> Threads that contain that word.
                for thread_id in self.store.get_threads_for_word(node_id):
                    thread_score = activation * DEPTH_DECAY.get(next_depth, 0.03)

                    if thread_score <= 0.001:
                        continue

                    thread_scores[thread_id] = thread_scores.get(thread_id, 0.0) + thread_score
                    add_activated_by(thread_activated_by, thread_id, f"word:{node_id}")
                    record_trace("word", node_id, "thread", thread_id, next_depth, thread_score, "word->thread")

                    # Process the same thread once per search unless a stronger activation arrives.
                    if thread_score > visited_thread.get(thread_id, 0.0):
                        visited_thread[thread_id] = thread_score
                        queue.append(("thread", thread_id, thread_score, next_depth, f"word:{node_id}"))

            elif node_type == "thread":
                # Thread -> Words inside that thread.
                for mem in self.store.get_thread_words(node_id):
                    word_score = self._memory_score(mem, activation, depth=next_depth, now=now)
                    if word_score <= 0.001:
                        continue

                    add_word_activation_v04(
                        word_scores, word_best_depth, word_threads, word_reasons, word_activated_by,
                        mem.word, mem.thread_id, word_score, next_depth, f"thread:{node_id}", f"thread:{node_id}"
                    )
                    record_trace("thread", node_id, "word", mem.word, next_depth, word_score, "thread->word")

                    if word_score > visited_word.get(mem.word, 0.0):
                        visited_word[mem.word] = word_score
                        queue.append(("word", mem.word, word_score, next_depth, f"thread:{node_id}"))

        activated_words = [
            ActivatedWord(
                word=w,
                score=s,
                best_depth=word_best_depth.get(w, 99),
                thread_ids=sorted(word_threads.get(w, set())),
                reasons=word_reasons.get(w, [])[:6],
                activated_by=word_activated_by.get(w, [])[:6],
            )
            for w, s in sorted(word_scores.items(), key=lambda kv: kv[1], reverse=True)
            if s > 0.001
        ][:top_words]

        activated_threads: list[ActivatedThread] = []
        for thread_id, score in sorted(thread_scores.items(), key=lambda kv: kv[1], reverse=True)[:top_threads]:
            thread = self.store.get_thread(thread_id)
            if thread is None:
                continue
            activated_threads.append(
                ActivatedThread(
                    thread_id=thread_id,
                    score=score,
                    words=thread.words,
                    date=thread.date,
                    activated_by=thread_activated_by.get(thread_id, [])[:6],
                )
            )

        return ActivationResult(
            input_words=input_words,
            activated_words=activated_words,
            activated_threads=activated_threads,
            traces=traces,
        )

    def _memory_score(self, mem: WordMemory, input_activation: float, depth: int, now: str) -> float:
        depth_decay = DEPTH_DECAY.get(depth, 0.03)
        days = max(days_between_iso(mem.last_seen, now), 0.0)
        time_decay = math.exp(-days / self.half_life_days)
        return input_activation * mem.weight * mem.strength * depth_decay * time_decay


class ResponseGenerator:
    def __init__(
        self,
        base_url: str | None = None,
        api_key: str | None = None,
        model: str | None = None,
        timeout_sec: float = 45.0,
    ) -> None:
        self.base_url = normalize_llm_base_url(base_url or os.getenv("LLM_BASE_URL") or "")
        self.api_key = api_key or os.getenv("LLM_API_KEY") or ""
        self.model = model or os.getenv("LLM_MODEL") or "local-model"
        self.timeout_sec = timeout_sec

    def generate(self, user_input: str, activation: ActivationResult) -> str:
        prompt = build_response_prompt(user_input, activation)
        if self.base_url:
            try:
                print(f"[llm] generating response via {self.base_url} model={self.model}", file=sys.stderr)
                return call_openai_compatible_chat(
                    base_url=self.base_url,
                    api_key=self.api_key,
                    model=self.model,
                    messages=[
                        {
                            "role": "system",
                            "content": (
                                "あなたは日本語で自然に短く返す会話相手です。\n"
                                "Activated Words and Threads are associative memory traces.\n"
                                "Do not treat them as exact quoted memories.\n"
                                "Use them as hints for natural recall and response.\n"
                                "断定しすぎず、自然な想起として返答してください。\n"
                                "返答は1〜3文。"
                            ),
                        },
                        {"role": "user", "content": prompt},
                    ],
                    temperature=0.7,
                    max_tokens=512,
                    timeout_sec=self.timeout_sec,
                ).strip()
            except Exception as exc:
                print(f"[warn] LLM response generation failed, fallback used: {exc}", file=sys.stderr)

        return fallback_generate_response(user_input, activation)


def add_activated_by(target: dict[str, list[str]], key: str, value: str) -> None:
    target.setdefault(key, [])
    if value not in target[key]:
        target[key].append(value)


def add_word_activation_v04(
    word_scores: dict[str, float],
    word_best_depth: dict[str, int],
    word_threads: dict[str, set[str]],
    word_reasons: dict[str, list[str]],
    word_activated_by: dict[str, list[str]],
    word: str,
    thread_id: str,
    score: float,
    depth: int,
    reason: str,
    activated_by: str,
) -> None:
    if score <= 0:
        return
    word_scores[word] = word_scores.get(word, 0.0) + score
    word_best_depth[word] = min(word_best_depth.get(word, 99), depth)
    word_threads.setdefault(word, set()).add(thread_id)
    word_reasons.setdefault(word, [])
    if reason not in word_reasons[word]:
        word_reasons[word].append(reason)
    add_activated_by(word_activated_by, word, activated_by)


def build_response_prompt(user_input: str, activation: ActivationResult) -> str:
    lines: list[str] = []
    lines.append("[Current Input]")
    lines.append(user_input)
    lines.append("")
    lines.append("[Extracted Input Words]")
    for w in activation.input_words:
        lines.append(f"- {w.word} ({w.weight:.2f})")

    lines.append("")
    lines.append("[Activated Words]")
    for aw in activation.activated_words:
        by = ", ".join(aw.activated_by[:3])
        lines.append(f"- {aw.word} score={aw.score:.3f} depth={aw.best_depth} activated_by={by}")

    lines.append("")
    lines.append("[Activated Threads]")
    for th in activation.activated_threads:
        words = " / ".join(th.words)
        by = ", ".join(th.activated_by[:3])
        lines.append(f"{th.thread_id}: {words} activated_by={by}")

    lines.append("")
    lines.append("[Activation Trace]")
    for tr in activation.traces[:40]:
        lines.append(f"- d{tr.depth}: {tr.from_type}:{tr.from_id} -> {tr.to_type}:{tr.to_id} score={tr.score:.3f}")

    lines.append("")
    lines.append("[Instruction]")
    lines.append("励起された単語とthreadは、正確な文章記憶ではなく連想の手がかりである。")
    lines.append("意味ラベルを勝手に保存情報として扱わない。")
    lines.append("ただし自然な会話として、思い出したように短く返す。")
    return "\n".join(lines)


def print_activation(result: ActivationResult) -> None:
    print("\n[Input Words]")
    for w in result.input_words:
        print(f"- {w.word} weight={w.weight:.2f}")

    print("\n[Activated Words]")
    for aw in result.activated_words:
        tids = ", ".join(aw.thread_ids[:3])
        by = ", ".join(aw.activated_by[:4]) if aw.activated_by else "-"
        print(f"- {aw.word} score={aw.score:.4f} depth={aw.best_depth} activated_by={by} threads={tids}")

    print("\n[Activated Threads]")
    for th in result.activated_threads:
        by = ", ".join(th.activated_by[:4]) if th.activated_by else "-"
        print(f"- {th.thread_id} score={th.score:.4f} activated_by={by} date={th.date}: {' / '.join(th.words)}")

    print("\n[Activation Trace]")
    if not result.traces:
        print("- (no trace)")
    for tr in result.traces[:80]:
        print(
            f"- d{tr.depth}: {tr.from_type}:{tr.from_id} -> "
            f"{tr.to_type}:{tr.to_id} score={tr.score:.4f} reason={tr.reason}"
        )


def check_openai_compatible_health(base_url: str, timeout_sec: float = 3.0) -> tuple[bool, str]:
    """
    Lightweight connectivity check.
    It does not call chat/completions because local LLM generation may take a long time.
    """
    base_url = normalize_llm_base_url(base_url)
    if not base_url:
        return False, "base_url is empty"

    candidates = []
    if base_url.endswith("/v1"):
        root = base_url[:-3]
        candidates.extend([
            root + "/health",
            root + "/v1/models",
            base_url + "/models",
        ])
    else:
        candidates.extend([
            base_url + "/health",
            base_url + "/v1/models",
            base_url + "/models",
        ])

    last_error = ""
    for url in candidates:
        try:
            req = urllib.request.Request(url=url, method="GET")
            with open_url_direct(req, timeout=timeout_sec) as resp:
                status = getattr(resp, "status", 200)
                body = resp.read(200).decode("utf-8", errors="replace")
                return True, f"GET {url} -> HTTP {status} {body[:120]}"
        except Exception as exc:
            last_error = f"GET {url} failed: {exc}"

    return False, last_error


def call_openai_compatible_chat(
    base_url: str,
    api_key: str,
    model: str,
    messages: list[dict[str, str]],
    temperature: float,
    max_tokens: int,
    timeout_sec: float,
) -> str:
    url = base_url.rstrip("/") + "/chat/completions"
    payload = {
        "model": model,
        "messages": messages,
        "temperature": temperature,
        "max_tokens": max_tokens,
        "stream": False,
    }

    headers = {"Content-Type": "application/json"}
    if api_key:
        headers["Authorization"] = f"Bearer {api_key}"

    req = urllib.request.Request(
        url=url,
        data=json.dumps(payload, ensure_ascii=False).encode("utf-8"),
        headers=headers,
        method="POST",
    )

    with open_url_direct(req, timeout=timeout_sec) as resp:
        raw = resp.read().decode("utf-8")

    data = json.loads(raw)
    return data["choices"][0]["message"]["content"]


def parse_json_object(text: str) -> dict[str, Any]:
    text = text.strip()
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass

    match = re.search(r"\{.*\}", text, flags=re.DOTALL)
    if not match:
        raise ValueError("No JSON object found in LLM output.")
    return json.loads(match.group(0))


def fallback_extract_words(text: str) -> list[ExtractedWord]:
    """
    Probe用の簡易抽出。
    本命はLLM抽出だが、LLMなしでも励起機構を試せるようにする。
    """
    text = normalize_text(text)

    replacements = {
        "ケーキ": ["ケーキ"],
        "カッター": ["カッター", "カッターナイフ"],
    }

    protected_terms = [
        "みつき",
        "チーズケーキ",
        "カッターナイフ",
        "カッター",
        "カフェ",
        "怪我",
        "苦手",
        "好き",
        "過去",
        "昔",
        "帰り",
        "作業",
        "ギター",
        "猫",
        "ソラ",
        "映画",
        "SF",
        "誕生日",
    ]

    found: list[ExtractedWord] = []
    for term in protected_terms:
        if term in text:
            weight = 1.2 if len(term) >= 4 else 1.0
            found.append(ExtractedWord(term, weight))

    # Japanese chunks / alnum chunks.
    chunks = re.findall(r"[A-Za-z0-9]+|[ぁ-んァ-ン一-龥ー]{2,}", text)
    stop = {
        "です", "ます", "だった", "って", "何だった", "これ", "それ", "あれ",
        "今日", "明日", "昨日", "する", "した", "ある", "いる", "行きたい",
        "使う", "少し", "かな", "だよ", "だね", "たいな",
    }

    for ch in chunks:
        ch = normalize_word(ch)
        if not ch or ch in stop:
            continue
        if len(ch) <= 1:
            continue

        # Avoid storing full Japanese sentence-like chunks in fallback mode.
        # LLM extraction should produce clean words; fallback must not pollute the DB
        # with phrases such as "みつきはチーズケーキが好き".
        if len(ch) >= 8 and re.search(r"[はがをにへでとてもやの]", ch):
            continue

        if any(ch in term and ch != term for term in protected_terms):
            continue
        found.append(ExtractedWord(ch, 0.8))

    expanded: list[ExtractedWord] = []
    for item in found:
        expanded.append(item)
        for alias in replacements.get(item.word, []):
            expanded.append(ExtractedWord(alias, item.weight * 0.9))

    return dedupe_extracted_words(expanded)


def dedupe_extracted_words(words: list[ExtractedWord]) -> list[ExtractedWord]:
    d: dict[str, float] = {}
    for item in words:
        word = normalize_word(item.word)
        if not word:
            continue
        d[word] = max(d.get(word, 0.0), clamp(item.weight, 0.1, 2.0))
    return [ExtractedWord(word=w, weight=weight) for w, weight in sorted(d.items(), key=lambda kv: kv[1], reverse=True)]


def match_known_words(input_word: str, known_words: list[str]) -> list[tuple[str, float]]:
    input_word = normalize_word(input_word)
    if not input_word:
        return []

    result: list[tuple[str, float]] = []
    for known in known_words:
        if input_word == known:
            result.append((known, 1.0))
        elif input_word in known or known in input_word:
            # 例: ケーキ → チーズケーキ、カッター → カッターナイフ
            short_len = max(min(len(input_word), len(known)), 1)
            long_len = max(max(len(input_word), len(known)), 1)
            sim = 0.72 + 0.20 * (short_len / long_len)
            result.append((known, clamp(sim, 0.55, 0.92)))
        elif loose_katakana_match(input_word, known):
            result.append((known, 0.72))

    result.sort(key=lambda x: x[1], reverse=True)
    return result[:12]


def loose_katakana_match(a: str, b: str) -> bool:
    a2 = a.replace("ー", "")
    b2 = b.replace("ー", "")
    return len(a2) >= 3 and len(b2) >= 3 and (a2 in b2 or b2 in a2)


def fallback_generate_response(user_input: str, activation: ActivationResult) -> str:
    top = [w.word for w in activation.activated_words[:5]]
    if not top:
        return "まだうまく思い出せないけど、その話もう少し聞かせて。"

    if "チーズケーキ" in top:
        return "チーズケーキが出てきたよ。たぶん、みつきが好きって話とつながってる気がする。"
    if "カッターナイフ" in top or "カッター" in top:
        return "カッターとか怪我、苦手って単語が反応してる。前に少し嫌な記憶として残ってたのかも。"
    return "今反応してるのは、" + "、".join(top[:4]) + " あたりかな。そこから少し思い出せそう。"


def normalize_text(text: str) -> str:
    return text.strip().replace("　", " ")


def normalize_word(word: str) -> str:
    word = normalize_text(word)
    word = word.strip(" \t\r\n。、,.!?！？「」『』（）()[]【】")
    return word


def clamp(v: float, lo: float, hi: float) -> float:
    return max(lo, min(hi, v))


def now_iso() -> str:
    return dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds")


def days_between_iso(start: str, end: str) -> float:
    try:
        s = dt.datetime.fromisoformat(start)
        e = dt.datetime.fromisoformat(end)
    except Exception:
        return 0.0
    return max((e - s).total_seconds() / 86400.0, 0.0)


def row_to_word_memory(row: sqlite3.Row) -> WordMemory:
    return WordMemory(
        word=row["word"],
        thread_id=row["thread_id"],
        date=row["date"],
        strength=float(row["strength"]),
        weight=float(row["weight"]),
        last_seen=row["last_seen"],
        seen_count=int(row["seen_count"]),
    )


def build_components(args: argparse.Namespace) -> tuple[ThreadedConceptMemoryStore, WordExtractor, ActivationEngine, ResponseGenerator]:
    store = ThreadedConceptMemoryStore(args.db)
    extractor = WordExtractor(
        base_url=args.base_url,
        api_key=args.api_key,
        model=args.model,
        timeout_sec=args.timeout,
    )
    engine = ActivationEngine(
        store=store,
        half_life_days=args.half_life_days,
        max_depth=args.max_depth,
    )
    generator = ResponseGenerator(
        base_url=args.base_url,
        api_key=args.api_key,
        model=args.model,
        timeout_sec=args.timeout,
    )
    return store, extractor, engine, generator


def cmd_add(args: argparse.Namespace) -> int:
    store, extractor, _, _ = build_components(args)
    try:
        words = extractor.extract(args.text)
        thread_id = store.create_thread(words, source_text=args.text)
        print(f"saved: {thread_id}")
        print("words:", " / ".join(f"{w.word}({w.weight:.2f})" for w in words))
        return 0
    finally:
        store.close()


def cmd_ask(args: argparse.Namespace) -> int:
    store, extractor, engine, generator = build_components(args)
    try:
        words = extractor.extract(args.text)
        result = engine.activate(words, top_words=args.top_words, top_threads=args.top_threads)
        print_activation(result)

        if not args.no_reinforce:
            store.reinforce_seen(result.activated_words)

        if not args.no_response:
            print("\n[Response]")
            print(generator.generate(args.text, result))
        return 0
    finally:
        store.close()


def cmd_threads(args: argparse.Namespace) -> int:
    store = ThreadedConceptMemoryStore(args.db)
    try:
        for th in store.list_threads(args.limit):
            print(f"{th.thread_id} {th.date}: {' / '.join(th.words)}")
            if args.show_source:
                print(f"  source(debug only): {th.source_text}")
        return 0
    finally:
        store.close()


def cmd_chat(args: argparse.Namespace) -> int:
    store, extractor, engine, generator = build_components(args)
    try:
        print("Threaded Concept Memory Probe v0.4")
        print(f"LLM: {'enabled ' + normalize_llm_base_url(args.base_url) if normalize_llm_base_url(args.base_url) else 'disabled; fallback mode'}")
        print("HTTP proxy: bypassed for local/direct calls")
        print("Commands: /exit, /threads, /add <text>, /ask <text>")
        print("Default: input is treated as /ask, then stored as a new thread.")
        while True:
            try:
                text = input("\n> ").strip()
            except EOFError:
                print()
                break

            if not text:
                continue
            if text in {"/exit", "exit", "quit", "/quit"}:
                break
            if text == "/threads":
                for th in store.list_threads(20):
                    print(f"{th.thread_id} {th.date}: {' / '.join(th.words)}")
                continue

            mode = "ask_then_add"
            if text.startswith("/add "):
                mode = "add"
                text = text[5:].strip()
            elif text.startswith("/ask "):
                mode = "ask"
                text = text[5:].strip()

            words = extractor.extract(text)

            if mode in {"ask", "ask_then_add"}:
                result = engine.activate(words, top_words=args.top_words, top_threads=args.top_threads)
                print_activation(result)
                store.reinforce_seen(result.activated_words)
                print("\n[Response]")
                print(generator.generate(text, result))

            if mode in {"add", "ask_then_add"}:
                thread_id = store.create_thread(words, source_text=text)
                print(f"\n[saved] {thread_id}: " + " / ".join(w.word for w in words))

        return 0
    finally:
        store.close()


def cmd_seed_tests(args: argparse.Namespace) -> int:
    store, extractor, engine, generator = build_components(args)
    try:
        seeds = [
            "みつきはチーズケーキが好き",
            "帰りにカフェへ寄りたい",
            "帰りにカフェでチーズケーキを食べたい",
            "映画を見るときはポップコーンがほしい",
            "ポップコーンを食べながらカフェで休みたい",
            "昔カッターナイフで怪我をした",
            "カッターナイフは少し苦手",
        ]
        for s in seeds:
            words = extractor.extract(s)
            thread_id = store.create_thread(words, source_text=s)
            print(f"seed saved: {thread_id}: {s}")
            print("  words:", " / ".join(w.word for w in words))

        tests = [
            "カフェ行きたい",
            "映画楽しみ",
            "好きなケーキって何だったっけ？",
            "カッター使う作業がある",
        ]
        for t in tests:
            print("\n" + "=" * 60)
            print("[Test Input]", t)
            words = extractor.extract(t)
            result = engine.activate(words, top_words=args.top_words, top_threads=args.top_threads)
            print_activation(result)
            print("\n[Response]")
            print(generator.generate(t, result))
        return 0
    finally:
        store.close()




def cmd_config(args: argparse.Namespace) -> int:
    base_url = normalize_llm_base_url(args.base_url or args.chat_base_url or os.getenv("LLM_BASE_URL", ""))
    model = args.model or os.getenv("LLM_MODEL", "local-model")
    print("[LLM Config]")
    print(f"base_url: {base_url or '(not set; fallback mode)'}")
    print(f"model: {model}")
    print(f"api_key: {'set' if (args.api_key or os.getenv('LLM_API_KEY')) else '(not set)'}")
    print(f"NO_PROXY: {os.environ.get('NO_PROXY', '')}")
    print("proxy_mode: disabled for this script's HTTP calls")

    if not base_url:
        print("status: LLM disabled. Set --base-url or LLM_BASE_URL.")
        return 0

    ok, detail = check_openai_compatible_health(base_url, timeout_sec=min(args.timeout, 5.0))
    print("health:", "ok" if ok else "failed")
    print("detail:", detail)

    if not getattr(args, "generate_test", False):
        print("chat/completions generation test: skipped")
        print("Use config --generate-test only when the local model is already loaded and responsive.")
        return 0

    try:
        content = call_openai_compatible_chat(
            base_url=base_url,
            api_key=args.api_key or os.getenv("LLM_API_KEY", ""),
            model=model,
            messages=[
                {"role": "system", "content": "Return only JSON. No explanation."},
                {"role": "user", "content": "{\"ok\":true}"},
            ],
            temperature=0.0,
            max_tokens=16,
            timeout_sec=args.timeout,
        )
        print("generation: ok")
        print("sample:", content.strip()[:200])
    except TimeoutError as exc:
        print("generation: timeout")
        print("error:", exc)
    except Exception as exc:
        print("generation: failed")
        print("error:", exc)

    return 0


def make_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Threaded Concept Memory Probe v0")
    parser.add_argument("--db", default=DEFAULT_DB_PATH)
    parser.add_argument("--base-url", default=os.getenv("LLM_BASE_URL", ""), help="OpenAI-compatible base URL. Accepts either http://host:port or http://host:port/v1")
    parser.add_argument("--chat-base-url", default="", help="Alias for --base-url, for compatibility with existing probe commands.")
    parser.add_argument("--api-key", default=os.getenv("LLM_API_KEY", ""))
    parser.add_argument("--model", default=os.getenv("LLM_MODEL", "local-model"))
    parser.add_argument("--timeout", type=float, default=12.0)
    parser.add_argument("--half-life-days", type=float, default=DEFAULT_HALF_LIFE_DAYS)
    parser.add_argument("--max-depth", type=int, default=DEFAULT_MAX_DEPTH)
    parser.add_argument("--top-words", type=int, default=20)
    parser.add_argument("--top-threads", type=int, default=8)

    sub = parser.add_subparsers(dest="command", required=True)

    p_add = sub.add_parser("add")
    p_add.add_argument("text")
    p_add.set_defaults(func=cmd_add)

    p_ask = sub.add_parser("ask")
    p_ask.add_argument("text")
    p_ask.add_argument("--no-response", action="store_true")
    p_ask.add_argument("--no-reinforce", action="store_true")
    p_ask.set_defaults(func=cmd_ask)

    p_threads = sub.add_parser("threads")
    p_threads.add_argument("--limit", type=int, default=20)
    p_threads.add_argument("--show-source", action="store_true")
    p_threads.set_defaults(func=cmd_threads)

    p_chat = sub.add_parser("chat")
    p_chat.set_defaults(func=cmd_chat)

    p_seed = sub.add_parser("seed-tests")
    p_seed.set_defaults(func=cmd_seed_tests)

    p_config = sub.add_parser("config")
    p_config.add_argument("--generate-test", action="store_true", help="Actually call /v1/chat/completions. May be slow on local models.")
    p_config.set_defaults(func=cmd_config)

    return parser


def main(argv: Optional[list[str]] = None) -> int:
    parser = make_parser()
    args = parser.parse_args(argv)
    if getattr(args, "chat_base_url", "") and not getattr(args, "base_url", ""):
        args.base_url = args.chat_base_url
    elif getattr(args, "chat_base_url", ""):
        args.base_url = args.chat_base_url
    args.base_url = normalize_llm_base_url(args.base_url)
    return int(args.func(args))


if __name__ == "__main__":
    raise SystemExit(main())
