#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Threaded Concept Memory Probe v0.9.2

Unique Word Node + WordThread Link Table.

This version changes the memory model:

Word is unique.
Thread is an experience.
Word and Thread are connected by many-to-many links.

Activation propagates:

Word
 -> Thread
 -> Word
 -> Thread
 -> Word

A thread becomes stronger when multiple activated words point to the same thread.
This is the core experiment:

"交差する糸が強く震える"

v0.7 adds:
- common activation bonus for threads supported by multiple input words
- mutual amplification between words co-activated through the same strong thread
- response prompt grouping by strongest experience threads

v0.8 adds:
- Activation Gate before prompt construction
- raw activation can spread widely, but prompt candidates are narrowed
- direct input intersections are preferred
- depth2+ words are treated as supporting candidates

The goal is not document retrieval.
The goal is to verify whether natural associative recall can emerge from
interconnected experience threads.

Meaning is never stored.
Meaning is generated only by the LLM from activated concepts.
"""

from __future__ import annotations

import argparse
import csv
import datetime as dt
import json
import math
import os
import re
import sqlite3
import sys
import urllib.request
import uuid
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Optional


# This probe does not store sentences as memories.
# It stores unique words and links them to experience threads.
# Meaning, emotion, importance, and relationship interpretation
# must be generated by the LLM at runtime.

# このProbeは文章を記憶として保存しない。
# 単語は一意なノードとして保存し、経験を表すthreadへ多対多で紐づける。
# 重要性・感情・恋人らしさ・意味付けは保存しない。
# それらは現在入力と励起語群を受け取ったLLMが実行時に生成する。

# Recall strength and conversation exposure are separate.
# A trace can be easy to recall but still be suppressed from conversation
# if it has already been exposed too often recently.

# 思い出しやすさと、会話で出すべきかは別である。
# 強く励起したTraceでも、直近で何度も会話に出していれば抑制する。
# これは忘却ではなく、しつこさを避けるための会話制御である。


DEFAULT_DB_PATH = "threaded_concept_memory_probe_v0_9_2.db"
DEFAULT_HALF_LIFE_DAYS = 14.0
DEFAULT_MAX_STRENGTH = 2.0
DEFAULT_REINFORCE_AMOUNT = 0.10
DEFAULT_MAX_DEPTH = 3
FIXED_THREAD_STRENGTH_MODE = "count"

GENERIC_PERSON_TERMS = ("ユーザー", "user", "person_a", "Aさん")
DEFAULT_SEED_TESTS_FILE = Path(__file__).resolve().parent.parent / "eval_conversations" / "seed_tests_public.jsonl"

DEPTH_DECAY: dict[int, float] = {
    0: 1.00,
    1: 0.40,
    2: 0.15,
    3: 0.05,
    4: 0.02,
}


def enable_localhost_proxy_bypass() -> None:
    bypass_hosts = ["127.0.0.1", "localhost", "::1", "0.0.0.0"]
    existing = os.environ.get("NO_PROXY") or os.environ.get("no_proxy") or ""
    parts = [p.strip() for p in existing.split(",") if p.strip()]
    for host in bypass_hosts:
        if host not in parts:
            parts.append(host)
    value = ",".join(parts)
    os.environ["NO_PROXY"] = value
    os.environ["no_proxy"] = value


def open_url_direct(req: urllib.request.Request, timeout: float):
    opener = urllib.request.build_opener(urllib.request.ProxyHandler({}))
    return opener.open(req, timeout=timeout)


enable_localhost_proxy_bypass()


def normalize_llm_base_url(value: str | None) -> str:
    if not value:
        return ""
    url = value.strip().rstrip("/")
    if not url:
        return ""
    if url.endswith("/chat/completions"):
        url = url[: -len("/chat/completions")]
    if not url.endswith("/v1"):
        url += "/v1"
    return url


@dataclass
class WordNode:
    word_id: str
    word: str
    strength: float
    weight: float
    seen_count: int
    first_seen: str
    last_seen: str


@dataclass
class Thread:
    thread_id: str
    date: str
    source_text: str | None
    words: list[str]
    canonical_key: str = ""
    strength: float = 1.0
    created_at: str = ""
    last_seen: str = ""
    seen_count: int = 1


@dataclass
class WordThreadLink:
    word_id: str
    word: str
    thread_id: str
    weight_in_thread: float
    added_at: str


@dataclass
class ExtractedWord:
    word: str
    weight: float


@dataclass
class ActivationTrace:
    from_type: str
    from_id: str
    to_type: str
    to_id: str
    depth: int
    score: float
    reason: str


@dataclass
class ActivatedWord:
    word: str
    score: float
    best_depth: int
    thread_ids: list[str]
    activated_by: list[str]


@dataclass
class ActivatedThread:
    thread_id: str
    score: float
    base_score: float
    common_bonus: float
    words: list[str]
    matched_words: list[str]
    activated_by: list[str]
    date: str
    canonical_key: str = ""
    thread_strength: float = 1.0
    effective_strength: float = 1.0
    same_key_thread_count: int = 1


@dataclass
class ActivationResult:
    input_words: list[ExtractedWord]
    activated_words: list[ActivatedWord]
    activated_threads: list[ActivatedThread]
    traces: list[ActivationTrace]


@dataclass
class GatedWord:
    word: str
    score: float
    depth: int
    role: str
    reason: str
    fatigue: int = 0
    suppressed_by_fatigue: bool = False


@dataclass
class GatedThread:
    thread_id: str
    score: float
    base_score: float
    common_bonus: float
    words: list[str]
    direct_words: list[str]
    core_words: list[str]
    support_words: list[str]
    suppressed_words: list[str]
    canonical_key: str = ""
    effective_strength: float = 1.0
    same_key_thread_count: int = 1


@dataclass
class GatedThreadGroup:
    canonical_key: str
    representative_thread_id: str
    occurrence_count: int
    score: float
    group_score: float
    base_score: float
    common_bonus: float
    effective_strength: float
    words: list[str]
    direct_words: list[str]
    core_words: list[str]
    support_words: list[str]
    suppressed_words: list[str]
    member_thread_ids: list[str]


@dataclass
class GatedContext:
    threads: list[GatedThreadGroup]
    words: list[GatedWord]
    suppressed_words: list[GatedWord]
    summary: str


class ThreadedConceptMemoryStore:
    def __init__(self, db_path: str = DEFAULT_DB_PATH) -> None:
        self.db_path = db_path
        self.conn = sqlite3.connect(db_path)
        self.conn.row_factory = sqlite3.Row
        self.init_schema()

    def _ensure_thread_columns(self) -> None:
        cur = self.conn.cursor()
        cols = {row["name"] for row in cur.execute("PRAGMA table_info(threads)").fetchall()}
        migrations = {
            "canonical_key": "ALTER TABLE threads ADD COLUMN canonical_key TEXT",
            "strength": "ALTER TABLE threads ADD COLUMN strength REAL NOT NULL DEFAULT 1.0",
            "created_at": "ALTER TABLE threads ADD COLUMN created_at TEXT",
            "last_seen": "ALTER TABLE threads ADD COLUMN last_seen TEXT",
            "seen_count": "ALTER TABLE threads ADD COLUMN seen_count INTEGER NOT NULL DEFAULT 1",
        }
        for col, sql in migrations.items():
            if col not in cols:
                cur.execute(sql)
        self.conn.commit()


    def _ensure_exposure_columns(self) -> None:
        cur = self.conn.cursor()
        cols = {row["name"] for row in cur.execute("PRAGMA table_info(conversation_exposures)").fetchall()}
        migrations = {
            "canonical_key": "ALTER TABLE conversation_exposures ADD COLUMN canonical_key TEXT",
            "exposure_type": "ALTER TABLE conversation_exposures ADD COLUMN exposure_type TEXT NOT NULL DEFAULT 'prompt'",
        }
        for col, sql in migrations.items():
            if col not in cols:
                cur.execute(sql)
        self.conn.commit()

    def close(self) -> None:
        self.conn.close()

    def init_schema(self) -> None:
        cur = self.conn.cursor()

        cur.execute(
            """
            CREATE TABLE IF NOT EXISTS words (
                word_id TEXT PRIMARY KEY,
                word TEXT UNIQUE NOT NULL,
                strength REAL NOT NULL DEFAULT 1.0,
                weight REAL NOT NULL DEFAULT 1.0,
                seen_count INTEGER NOT NULL DEFAULT 1,
                first_seen TEXT NOT NULL,
                last_seen TEXT NOT NULL
            )
            """
        )

        cur.execute(
            """
            CREATE TABLE IF NOT EXISTS threads (
                thread_id TEXT PRIMARY KEY,
                date TEXT NOT NULL,
                source_text TEXT,
                canonical_key TEXT,
                strength REAL NOT NULL DEFAULT 1.0,
                created_at TEXT,
                last_seen TEXT,
                seen_count INTEGER NOT NULL DEFAULT 1
            )
            """
        )

        cur.execute(
            """
            CREATE TABLE IF NOT EXISTS conversation_exposures (
                id TEXT PRIMARY KEY,
                word TEXT,
                thread_id TEXT,
                canonical_key TEXT,
                exposure_type TEXT NOT NULL DEFAULT 'prompt',
                exposed_at TEXT NOT NULL,
                turn_no INTEGER NOT NULL
            )
            """
        )

        self._ensure_thread_columns()
        self._ensure_exposure_columns()

        cur.execute(
            """
            CREATE TABLE IF NOT EXISTS word_threads (
                word_id TEXT NOT NULL,
                thread_id TEXT NOT NULL,
                weight_in_thread REAL NOT NULL DEFAULT 1.0,
                added_at TEXT NOT NULL,
                PRIMARY KEY (word_id, thread_id),
                FOREIGN KEY (word_id) REFERENCES words(word_id),
                FOREIGN KEY (thread_id) REFERENCES threads(thread_id)
            )
            """
        )

        cur.execute("CREATE INDEX IF NOT EXISTS idx_words_word ON words(word)")
        cur.execute("CREATE INDEX IF NOT EXISTS idx_word_threads_word ON word_threads(word_id)")
        cur.execute("CREATE INDEX IF NOT EXISTS idx_word_threads_thread ON word_threads(thread_id)")
        cur.execute("CREATE INDEX IF NOT EXISTS idx_threads_canonical_key ON threads(canonical_key)")
        cur.execute("CREATE INDEX IF NOT EXISTS idx_conversation_exposures_turn ON conversation_exposures(turn_no)")
        cur.execute("CREATE INDEX IF NOT EXISTS idx_conversation_exposures_word ON conversation_exposures(word)")
        self.conn.commit()

    def create_thread(self, words: list[ExtractedWord], source_text: str | None, thread_strength_mode: str = "count") -> str:
        now = now_iso()
        date = now[:10]
        thread_strength_mode = normalize_thread_strength_mode(thread_strength_mode)

        normalized: dict[str, float] = {}
        for item in words:
            word = normalize_word(item.word)
            if not word:
                continue
            weight = clamp(float(item.weight), 0.1, 2.0)
            normalized[word] = max(normalized.get(word, 0.0), weight)

        if any(person in normalized for person in GENERIC_PERSON_TERMS):
            for w in list(normalized.keys()):
                normalized[w] = clamp(normalized[w] * 1.15, 0.1, 2.3)

        canonical_key = make_canonical_key(normalized.keys())
        cur = self.conn.cursor()

        if thread_strength_mode == "weighted" and canonical_key:
            existing = cur.execute(
                """
                SELECT thread_id, strength, seen_count
                FROM threads
                WHERE canonical_key = ?
                ORDER BY created_at ASC, rowid ASC
                LIMIT 1
                """,
                (canonical_key,),
            ).fetchone()
            if existing is not None:
                thread_id = existing["thread_id"]
                cur.execute(
                    """
                    UPDATE threads
                    SET strength = ?, seen_count = ?, last_seen = ?
                    WHERE thread_id = ?
                    """,
                    (min(float(existing["strength"]) + 0.45, 4.0), int(existing["seen_count"]) + 1, now, thread_id),
                )
                for word, weight in normalized.items():
                    self._upsert_word_node(cur, word, weight, now)
                self.conn.commit()
                return thread_id

        thread_id = "thread_" + uuid.uuid4().hex[:12]
        cur.execute(
            """
            INSERT INTO threads(thread_id, date, source_text, canonical_key, strength, created_at, last_seen, seen_count)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (thread_id, date, source_text, canonical_key, 1.0, now, now, 1),
        )

        for word, weight in normalized.items():
            word_id = self._upsert_word_node(cur, word, weight, now)
            cur.execute(
                """
                INSERT OR REPLACE INTO word_threads(word_id, thread_id, weight_in_thread, added_at)
                VALUES (?, ?, ?, ?)
                """,
                (word_id, thread_id, weight, now),
            )
        self.conn.commit()
        return thread_id

    def _upsert_word_node(self, cur: sqlite3.Cursor, word: str, weight: float, now: str) -> str:
        node = self.get_word_by_text(word)
        if node is None:
            word_id = "word_" + uuid.uuid4().hex[:12]
            cur.execute(
                """
                INSERT INTO words(word_id, word, strength, weight, seen_count, first_seen, last_seen)
                VALUES (?, ?, ?, ?, ?, ?, ?)
                """,
                (word_id, word, 1.0, weight, 1, now, now),
            )
            return word_id
        word_id = node.word_id
        cur.execute(
            """
            UPDATE words
            SET strength = ?, weight = ?, seen_count = ?, last_seen = ?
            WHERE word_id = ?
            """,
            (min(node.strength + DEFAULT_REINFORCE_AMOUNT, DEFAULT_MAX_STRENGTH), max(node.weight, weight), node.seen_count + 1, now, word_id),
        )
        return word_id

    def get_word_by_text(self, word: str) -> Optional[WordNode]:
        row = self.conn.execute(
            """
            SELECT word_id, word, strength, weight, seen_count, first_seen, last_seen
            FROM words
            WHERE word = ?
            """,
            (word,),
        ).fetchone()
        return row_to_word_node(row) if row else None

    def get_word_by_id(self, word_id: str) -> Optional[WordNode]:
        row = self.conn.execute(
            """
            SELECT word_id, word, strength, weight, seen_count, first_seen, last_seen
            FROM words
            WHERE word_id = ?
            """,
            (word_id,),
        ).fetchone()
        return row_to_word_node(row) if row else None

    def get_all_words(self) -> list[str]:
        rows = self.conn.execute("SELECT word FROM words ORDER BY word").fetchall()
        return [r["word"] for r in rows]

    def get_links_for_word(self, word_id: str) -> list[WordThreadLink]:
        rows = self.conn.execute(
            """
            SELECT wt.word_id, w.word, wt.thread_id, wt.weight_in_thread, wt.added_at
            FROM word_threads wt
            JOIN words w ON w.word_id = wt.word_id
            WHERE wt.word_id = ?
            ORDER BY wt.weight_in_thread DESC
            """,
            (word_id,),
        ).fetchall()
        return [row_to_word_thread_link(r) for r in rows]

    def get_links_for_thread(self, thread_id: str) -> list[WordThreadLink]:
        rows = self.conn.execute(
            """
            SELECT wt.word_id, w.word, wt.thread_id, wt.weight_in_thread, wt.added_at
            FROM word_threads wt
            JOIN words w ON w.word_id = wt.word_id
            WHERE wt.thread_id = ?
            ORDER BY wt.weight_in_thread DESC, w.word ASC
            """,
            (thread_id,),
        ).fetchall()
        return [row_to_word_thread_link(r) for r in rows]

    def get_thread(self, thread_id: str) -> Optional[Thread]:
        row = self.conn.execute(
            """
            SELECT thread_id, date, source_text, canonical_key, strength, created_at, last_seen, seen_count
            FROM threads
            WHERE thread_id = ?
            """,
            (thread_id,),
        ).fetchone()
        if row is None:
            return None
        words = [link.word for link in self.get_links_for_thread(thread_id)]
        return Thread(
            thread_id=row["thread_id"],
            date=row["date"],
            source_text=row["source_text"],
            words=words,
            canonical_key=row["canonical_key"] or make_canonical_key(words),
            strength=float(row["strength"]),
            created_at=row["created_at"] or row["date"],
            last_seen=row["last_seen"] or row["date"],
            seen_count=int(row["seen_count"]),
        )

    def list_threads(self, limit: int = 20) -> list[Thread]:
        rows = self.conn.execute(
            """
            SELECT thread_id, date, source_text
            FROM threads
            ORDER BY rowid DESC
            LIMIT ?
            """,
            (limit,),
        ).fetchall()
        result: list[Thread] = []
        for r in rows:
            th = self.get_thread(r["thread_id"])
            if th is not None:
                result.append(th)
        return result

    def list_words(self, limit: int = 100) -> list[WordNode]:
        rows = self.conn.execute(
            """
            SELECT word_id, word, strength, weight, seen_count, first_seen, last_seen
            FROM words
            ORDER BY seen_count DESC, word ASC
            LIMIT ?
            """,
            (limit,),
        ).fetchall()
        return [row_to_word_node(r) for r in rows]

    def count_threads_by_canonical_key(self, canonical_key: str) -> int:
        if not canonical_key:
            return 1
        row = self.conn.execute("SELECT COUNT(*) AS c FROM threads WHERE canonical_key = ?", (canonical_key,)).fetchone()
        return int(row["c"]) if row else 1

    def get_next_turn_no(self) -> int:
        row = self.conn.execute("SELECT COALESCE(MAX(turn_no), 0) + 1 AS next_turn FROM conversation_exposures").fetchone()
        return int(row["next_turn"]) if row else 1

    def get_fatigue(self, word: str, recent_turns: int = 10, exposure_type: str = "prompt") -> int:
        next_turn = self.get_next_turn_no()
        min_turn = max(1, next_turn - recent_turns)
        row = self.conn.execute(
            "SELECT COUNT(*) AS c FROM conversation_exposures WHERE word = ? AND turn_no >= ? AND exposure_type = ?",
            (word, min_turn, exposure_type),
        ).fetchone()
        return int(row["c"]) if row else 0

    def get_fatigue_prompt(self, word: str, recent_turns: int = 10) -> int:
        return self.get_fatigue(word, recent_turns, "prompt")

    def get_fatigue_response(self, word: str, recent_turns: int = 10) -> int:
        return self.get_fatigue(word, recent_turns, "response")

    def record_exposures(self, gated: GatedContext, turn_no: Optional[int] = None, exposure_type: str = "prompt", response_text: str = "") -> int:
        if turn_no is None:
            turn_no = self.get_next_turn_no()
        now = now_iso()
        cur = self.conn.cursor()
        for gw in gated.words:
            if gw.suppressed_by_fatigue:
                continue
            if exposure_type == "response" and response_text and gw.word not in response_text:
                continue
            cur.execute(
                "INSERT INTO conversation_exposures(id, word, thread_id, canonical_key, exposure_type, exposed_at, turn_no) VALUES (?, ?, ?, ?, ?, ?, ?)",
                ("exp_" + uuid.uuid4().hex[:12], gw.word, None, None, exposure_type, now, turn_no),
            )
        if exposure_type == "prompt":
            for th in gated.threads:
                cur.execute(
                    "INSERT INTO conversation_exposures(id, word, thread_id, canonical_key, exposure_type, exposed_at, turn_no) VALUES (?, ?, ?, ?, ?, ?, ?)",
                    ("exp_" + uuid.uuid4().hex[:12], None, th.representative_thread_id, th.canonical_key, exposure_type, now, turn_no),
                )
        self.conn.commit()
        return turn_no

    def reinforce_seen(self, activated_words: list[ActivatedWord]) -> None:
        now = now_iso()
        cur = self.conn.cursor()
        for aw in activated_words:
            node = self.get_word_by_text(aw.word)
            if node is None:
                continue
            # Depthが浅いほど強化。score自体は爆発しうるためlogで抑える。
            gain = DEFAULT_REINFORCE_AMOUNT * (1.0 / (1.0 + aw.best_depth)) * min(math.log1p(aw.score), 1.0)
            cur.execute(
                """
                UPDATE words
                SET strength = ?, seen_count = ?, last_seen = ?
                WHERE word_id = ?
                """,
                (
                    min(node.strength + gain, DEFAULT_MAX_STRENGTH),
                    node.seen_count + 1,
                    now,
                    node.word_id,
                ),
            )
        self.conn.commit()


class WordExtractor:
    def __init__(self, base_url: str = "", api_key: str = "", model: str = "local-model", timeout_sec: float = 12.0) -> None:
        self.base_url = normalize_llm_base_url(base_url or os.getenv("LLM_BASE_URL", ""))
        self.api_key = api_key or os.getenv("LLM_API_KEY", "")
        self.model = model or os.getenv("LLM_MODEL", "local-model")
        self.timeout_sec = timeout_sec

    def extract(self, text: str) -> list[ExtractedWord]:
        if self.base_url:
            try:
                print(f"[llm] extracting words via {self.base_url} model={self.model}", file=sys.stderr)
                return self._extract_with_llm(text)
            except Exception as exc:
                print(f"[warn] LLM word extraction failed, fallback used: {exc}", file=sys.stderr)
        return fallback_extract_words(text)

    def _extract_with_llm(self, text: str) -> list[ExtractedWord]:
        system = (
            "You extract Japanese memory trigger words from a user utterance.\n"
            "Do not classify words. Do not infer relationship labels.\n"
            "Return strict JSON only.\n"
            "Schema: {\"words\":[{\"word\":\"...\",\"weight\":1.0}]}\n"
            "Extract people, objects, actions, places, feelings, time words, and notable nouns/verbs/adjectives.\n"
            "Keep words short. Use base/common forms when natural.\n"
            "Weight range: 0.4 to 1.4. Important concrete words can be 1.2-1.4."
        )
        content = call_openai_compatible_chat(
            base_url=self.base_url,
            api_key=self.api_key,
            model=self.model,
            messages=[
                {"role": "system", "content": system},
                {"role": "user", "content": f"Input:\n{text}\n\nReturn JSON only."},
            ],
            temperature=0.0,
            max_tokens=256,
            timeout_sec=self.timeout_sec,
        )

        data = parse_json_object(content)
        words_raw = data.get("words", [])
        words: list[ExtractedWord] = []
        for item in words_raw:
            if not isinstance(item, dict):
                continue
            word = normalize_word(str(item.get("word", "")))
            if not word:
                continue
            try:
                weight = float(item.get("weight", 1.0))
            except Exception:
                weight = 1.0
            words.append(ExtractedWord(word, clamp(weight, 0.1, 2.0)))
        return dedupe_extracted_words(words) or fallback_extract_words(text)


class ActivationEngine:
    def __init__(
        self,
        store: ThreadedConceptMemoryStore,
        half_life_days: float = DEFAULT_HALF_LIFE_DAYS,
        max_depth: int = DEFAULT_MAX_DEPTH,
        common_bonus_multiplier: float = 0.45,
        mutual_amplification: float = 0.12,
        thread_strength_mode: str = "count",
    ) -> None:
        self.store = store
        self.half_life_days = half_life_days
        self.max_depth = max_depth
        self.common_bonus_multiplier = common_bonus_multiplier
        self.mutual_amplification = mutual_amplification
        self.thread_strength_mode = normalize_thread_strength_mode(thread_strength_mode)

    def activate(self, input_words: list[ExtractedWord], top_words: int = 20, top_threads: int = 8) -> ActivationResult:
        now = now_iso()
        known_words = self.store.get_all_words()
        direct_input_word_set = {normalize_word(w.word) for w in input_words if normalize_word(w.word)}

        word_scores: dict[str, float] = {}
        word_best_depth: dict[str, int] = {}
        word_threads: dict[str, set[str]] = {}
        word_activated_by: dict[str, list[str]] = {}

        # base thread score comes directly from propagation.
        # final thread score = base + common activation bonus.
        thread_base_scores: dict[str, float] = {}
        thread_scores: dict[str, float] = {}
        thread_matched_words: dict[str, set[str]] = {}
        thread_direct_matched_words: dict[str, set[str]] = {}
        thread_activated_by: dict[str, list[str]] = {}
        thread_common_bonus: dict[str, float] = {}

        traces: list[ActivationTrace] = []

        # Queue: node_type, node_id, score, depth
        queue: list[tuple[str, str, float, int]] = []

        # Use max-score visited, not once-only, because a later intersection may be stronger.
        visited_word_score: dict[str, float] = {}
        visited_thread_score: dict[str, float] = {}

        def record_trace(from_type: str, from_id: str, to_type: str, to_id: str, depth: int, score: float, reason: str) -> None:
            traces.append(ActivationTrace(from_type, from_id, to_type, to_id, depth, score, reason))

        # depth0: input word -> unique Word node.
        for iw in input_words:
            for matched_word, sim in match_known_words(iw.word, known_words):
                node = self.store.get_word_by_text(matched_word)
                if node is None:
                    continue
                score = self._word_score(node, iw.weight * sim, depth=0, now=now)

                add_word_activation(
                    word_scores, word_best_depth, word_threads, word_activated_by,
                    node.word, [], score, 0, f"input:{iw.word}"
                )
                record_trace("input", iw.word, "word", node.word, 0, score, f"matched sim={sim:.2f}")

                if score > visited_word_score.get(node.word_id, 0.0):
                    visited_word_score[node.word_id] = score
                    queue.append(("word", node.word_id, score, 0))

        while queue:
            node_type, node_id, score, depth = queue.pop(0)
            if depth >= self.max_depth:
                continue

            next_depth = depth + 1

            if node_type == "word":
                node = self.store.get_word_by_id(node_id)
                if node is None:
                    continue

                # Word -> all linked Threads.
                for link in self.store.get_links_for_word(node_id):
                    thread = self.store.get_thread(link.thread_id)
                    if thread is None:
                        continue
                    effective_strength = self._thread_effective_strength(thread, now)
                    thread_score = score * link.weight_in_thread * effective_strength * DEPTH_DECAY.get(next_depth, 0.03)
                    if thread_score <= 0.001:
                        continue

                    # Important:
                    # If multiple activated words point to the same thread,
                    # the thread score is accumulated.
                    thread_base_scores[link.thread_id] = thread_base_scores.get(link.thread_id, 0.0) + thread_score
                    thread_matched_words.setdefault(link.thread_id, set()).add(node.word)
                    if node.word in {w for w in known_words if w in direct_input_word_set} or node.word in direct_input_word_set:
                        thread_direct_matched_words.setdefault(link.thread_id, set()).add(node.word)
                    add_activated_by(thread_activated_by, link.thread_id, f"word:{node.word}")
                    record_trace("word", node.word, "thread", link.thread_id, next_depth, thread_score, "word->thread")

                    # Continue BFS only when this path is stronger than previous route.
                    if thread_score > visited_thread_score.get(link.thread_id, 0.0):
                        visited_thread_score[link.thread_id] = thread_score
                        queue.append(("thread", link.thread_id, thread_score, next_depth))

            elif node_type == "thread":
                thread_id = node_id

                # Thread -> all linked Words.
                for link in self.store.get_links_for_thread(thread_id):
                    node = self.store.get_word_by_id(link.word_id)
                    if node is None:
                        continue
                    word_score = self._word_score(node, score * link.weight_in_thread, depth=next_depth, now=now)
                    if word_score <= 0.001:
                        continue

                    add_word_activation(
                        word_scores, word_best_depth, word_threads, word_activated_by,
                        node.word, [thread_id], word_score, next_depth, f"thread:{thread_id}"
                    )
                    record_trace("thread", thread_id, "word", node.word, next_depth, word_score, "thread->word")

                    if word_score > visited_word_score.get(node.word_id, 0.0):
                        visited_word_score[node.word_id] = word_score
                        queue.append(("word", node.word_id, word_score, next_depth))

        # v0.7: Common activation bonus.
        # Threads supported by multiple directly activated/input words get a strong boost.
        # This makes "ユーザー + 好き" strongly prefer threads that contain both,
        # while "好き" only threads remain weaker.
        for thread_id, base in thread_base_scores.items():
            direct_count = len(thread_direct_matched_words.get(thread_id, set()))
            if direct_count >= 2:
                # quadratic-ish but controlled:
                # 2 direct words => + common_bonus_multiplier * base
                # 3 direct words => + 4x multiplier factor on base
                common_bonus = base * self.common_bonus_multiplier * ((direct_count - 1) ** 2)
            else:
                common_bonus = 0.0
            thread_common_bonus[thread_id] = common_bonus
            thread_scores[thread_id] = base + common_bonus
            if common_bonus > 0:
                record_trace(
                    "thread",
                    thread_id,
                    "thread",
                    thread_id,
                    0,
                    common_bonus,
                    f"common-bonus direct_matches={direct_count}",
                )

        # v0.7: Mutual amplification.
        # Strong threads softly amplify words inside them.
        # This is intentionally small; it should not turn weak noise into a main answer.
        for thread_id, final_score in thread_scores.items():
            if final_score <= 0:
                continue
            direct_count = len(thread_direct_matched_words.get(thread_id, set()))
            if direct_count <= 0:
                continue

            thread = self.store.get_thread(thread_id)
            if thread is None:
                continue

            # Only strong / jointly-supported threads should amplify noticeably.
            joint_factor = 1.0 + max(0, direct_count - 1)
            for link in self.store.get_links_for_thread(thread_id):
                node = self.store.get_word_by_id(link.word_id)
                if node is None:
                    continue
                # Avoid overboosting words that were already direct input anchors.
                if node.word in direct_input_word_set:
                    continue
                boost = final_score * self.mutual_amplification * link.weight_in_thread * 0.10 * joint_factor
                if boost <= 0.001:
                    continue
                add_word_activation(
                    word_scores,
                    word_best_depth,
                    word_threads,
                    word_activated_by,
                    node.word,
                    [thread_id],
                    boost,
                    2,
                    f"mutual:{thread_id}",
                )
                record_trace("thread", thread_id, "word", node.word, 2, boost, "mutual-amplification")

        activated_words = [
            ActivatedWord(
                word=w,
                score=s,
                best_depth=word_best_depth.get(w, 99),
                thread_ids=sorted(word_threads.get(w, set())),
                activated_by=word_activated_by.get(w, [])[:6],
            )
            for w, s in sorted(word_scores.items(), key=lambda kv: kv[1], reverse=True)
            if s > 0.001
        ][:top_words]

        activated_threads: list[ActivatedThread] = []
        for thread_id, score in sorted(thread_scores.items(), key=lambda kv: kv[1], reverse=True)[:top_threads]:
            thread = self.store.get_thread(thread_id)
            if thread is None:
                continue
            activated_threads.append(
                ActivatedThread(
                    thread_id=thread_id,
                    score=score,
                    base_score=thread_base_scores.get(thread_id, 0.0),
                    common_bonus=thread_common_bonus.get(thread_id, 0.0),
                    words=thread.words,
                    matched_words=sorted(thread_matched_words.get(thread_id, set())),
                    activated_by=thread_activated_by.get(thread_id, [])[:8],
                    date=thread.date,
                    canonical_key=thread.canonical_key,
                    thread_strength=thread.strength,
                    effective_strength=self._thread_effective_strength(thread, now),
                    same_key_thread_count=self.store.count_threads_by_canonical_key(thread.canonical_key),
                )
            )

        return ActivationResult(input_words, activated_words, activated_threads, traces)

    def _thread_effective_strength(self, thread: Thread, now: str) -> float:
        days = max(days_between_iso(thread.last_seen, now), 0.0)
        time_decay = math.exp(-days / self.half_life_days)
        if self.thread_strength_mode == "weighted":
            return thread.strength * time_decay
        return 1.0 * time_decay

    def _word_score(self, node: WordNode, activation: float, depth: int, now: str) -> float:
        days = max(days_between_iso(node.last_seen, now), 0.0)
        time_decay = math.exp(-days / self.half_life_days)
        return activation * node.weight * node.strength * DEPTH_DECAY.get(depth, 0.03) * time_decay



class ActivationGate:
    """
    v0.8 Prompt gate.

    Raw Activation may spread across multiple threads.
    The gate does not change the raw activation log.
    It only decides what becomes prompt-visible context.

    Policy:
    - Prefer top experience threads, not top loose words.
    - Prefer threads supported by multiple direct input words.
    - Direct words and thread-local core words are prompt-visible.
    - depth2+ words from weak threads become support or suppressed.
    - low-score words remain in logs but are not sent to the LLM.
    """

    def __init__(
        self,
        max_prompt_threads: int = 4,
        max_core_words_per_thread: int = 5,
        max_prompt_words: int = 12,
        min_thread_score: float = 0.05,
        min_word_score: float = 0.05,
        support_ratio: float = 0.18,
        store: Optional[ThreadedConceptMemoryStore] = None,
        fatigue_recent_turns: int = 10,
        fatigue_threshold: int = 3,
    ) -> None:
        self.max_prompt_threads = max_prompt_threads
        self.max_core_words_per_thread = max_core_words_per_thread
        self.max_prompt_words = max_prompt_words
        self.min_thread_score = min_thread_score
        self.min_word_score = min_word_score
        self.support_ratio = support_ratio
        self.store = store
        self.fatigue_recent_turns = fatigue_recent_turns
        self.fatigue_threshold = fatigue_threshold

    def gate(self, activation: ActivationResult) -> GatedContext:
        input_word_set = {normalize_word(w.word) for w in activation.input_words if normalize_word(w.word)}
        word_by_text = {w.word: w for w in activation.activated_words}

        def fatigue_prompt_for(word: str) -> int:
            if self.store is None:
                return 0
            return self.store.get_fatigue_prompt(word, self.fatigue_recent_turns)

        def fatigue_response_for(word: str) -> int:
            if self.store is None:
                return 0
            return self.store.get_fatigue_response(word, self.fatigue_recent_turns)

        def is_asked_override(word: str) -> bool:
            return word in input_word_set
        max_thread_score = max([t.score for t in activation.activated_threads], default=0.0)

        selected_threads: list[ActivatedThread] = []
        for th in activation.activated_threads:
            if len(selected_threads) >= self.max_prompt_threads:
                break
            if th.score < self.min_thread_score:
                continue

            direct_words = [w for w in th.matched_words if w in input_word_set]
            is_strong_enough = max_thread_score <= 0 or th.score >= max_thread_score * self.support_ratio
            if is_strong_enough or len(direct_words) >= 1 or th.common_bonus > 0:
                selected_threads.append(th)

        selected_thread_ids = {t.thread_id for t in selected_threads}

        preliminary_threads: list[GatedThread] = []
        visible_word_names: set[str] = set()
        suppressed_word_names: set[str] = set()

        for th in selected_threads:
            direct_words = [w for w in th.words if w in input_word_set]
            core_words: list[str] = []
            support_words: list[str] = []
            suppressed_words: list[str] = []

            sorted_thread_words = sorted(
                th.words,
                key=lambda word: (
                    1 if word in input_word_set else 0,
                    word_by_text.get(word).score if word in word_by_text else 0.0,
                ),
                reverse=True,
            )

            for word in sorted_thread_words:
                aw = word_by_text.get(word)
                score = aw.score if aw else 0.0

                if word in direct_words:
                    if word not in core_words:
                        core_words.append(word)
                        visible_word_names.add(word)
                    continue

                if len(core_words) < self.max_core_words_per_thread and score >= self.min_word_score:
                    core_words.append(word)
                    visible_word_names.add(word)
                elif score >= self.min_word_score:
                    support_words.append(word)
                    visible_word_names.add(word)
                else:
                    suppressed_words.append(word)
                    suppressed_word_names.add(word)

            preliminary_threads.append(
                GatedThread(
                    thread_id=th.thread_id,
                    score=th.score,
                    base_score=th.base_score,
                    common_bonus=th.common_bonus,
                    words=th.words,
                    direct_words=direct_words,
                    core_words=core_words[: self.max_core_words_per_thread],
                    support_words=support_words[: self.max_core_words_per_thread],
                    suppressed_words=suppressed_words,
                    canonical_key=th.canonical_key,
                    effective_strength=th.effective_strength,
                    same_key_thread_count=th.same_key_thread_count,
                )
            )

        # Count mode keeps repeated traces as separate threads internally,
        # but the prompt should receive them as one canonical ThreadGroup.
        # Repetition strengthens recall, but should not duplicate prompt content.
        #
        # count modeでは、内部的には同じ痕跡を複数threadとして保持する。
        # ただしPromptへ渡すときはcanonical_key単位で1つのThreadGroupに圧縮する。
        # 繰り返しは想起を強めるが、Prompt内容を重複させてはいけない。
        gated_threads = self._group_threads(preliminary_threads)

        gated_words: list[GatedWord] = []
        for aw in activation.activated_words:
            if len(gated_words) >= self.max_prompt_words:
                break

            in_selected_thread = any(tid in selected_thread_ids for tid in aw.thread_ids)
            is_direct = aw.word in input_word_set

            if aw.score < self.min_word_score and not is_direct:
                suppressed_word_names.add(aw.word)
                continue
            if not in_selected_thread and not is_direct:
                suppressed_word_names.add(aw.word)
                continue

            fatigue = fatigue_prompt_for(aw.word)
            fatigue_suppressed = fatigue >= self.fatigue_threshold and not is_asked_override(aw.word)
            if is_direct:
                role = "direct"
                reason = "input word / asked override" if fatigue_suppressed else "input word"
            elif fatigue_suppressed:
                suppressed_word_names.add(aw.word)
                continue
            elif aw.best_depth <= 2:
                role = "core"
                reason = "inside selected thread"
            else:
                role = "support"
                reason = "multi-hop support"

            gated_words.append(GatedWord(aw.word, aw.score, aw.best_depth, role, reason, fatigue, False))
            visible_word_names.add(aw.word)

        suppressed_words: list[GatedWord] = []
        for aw in activation.activated_words:
            if aw.word in visible_word_names:
                continue
            if aw.word in suppressed_word_names or aw.score < self.min_word_score:
                fatigue = fatigue_prompt_for(aw.word)
                fatigue_suppressed = fatigue >= self.fatigue_threshold and not is_asked_override(aw.word)
                reason = "recently_exposed" if fatigue_suppressed else "below gate or outside selected threads"
                suppressed_words.append(GatedWord(aw.word, aw.score, aw.best_depth, "suppressed", reason, fatigue, fatigue_suppressed))

        if gated_threads:
            if gated_threads[0].common_bonus > 0:
                summary = "Multiple input words converged on the top experience threads."
            else:
                summary = "A small set of related experience threads was selected."
        else:
            summary = "No strong gated context."

        return GatedContext(
            threads=gated_threads,
            words=gated_words,
            suppressed_words=suppressed_words[:20],
            summary=summary,
        )

    def _group_threads(self, threads: list[GatedThread]) -> list[GatedThreadGroup]:
        grouped: dict[str, list[GatedThread]] = {}
        for th in threads:
            key = th.canonical_key or make_canonical_key(th.words) or th.thread_id
            grouped.setdefault(key, []).append(th)

        result: list[GatedThreadGroup] = []
        for key, members in grouped.items():
            representative = max(members, key=lambda th: th.score)
            member_thread_ids = [th.thread_id for th in members]
            occurrence_count = max(representative.same_key_thread_count, len(members))
            group_score = sum(th.score for th in members)
            base_score = sum(th.base_score for th in members)
            common_bonus = sum(th.common_bonus for th in members)
            effective_strength = max(th.effective_strength for th in members)
            result.append(
                GatedThreadGroup(
                    canonical_key=key,
                    representative_thread_id=representative.thread_id,
                    occurrence_count=occurrence_count,
                    score=representative.score,
                    group_score=group_score,
                    base_score=base_score,
                    common_bonus=common_bonus,
                    effective_strength=effective_strength,
                    words=representative.words,
                    direct_words=merge_unique([w for th in members for w in th.direct_words]),
                    core_words=merge_unique([w for th in members for w in th.core_words])[: self.max_core_words_per_thread],
                    support_words=merge_unique([w for th in members for w in th.support_words])[: self.max_core_words_per_thread],
                    suppressed_words=merge_unique([w for th in members for w in th.suppressed_words]),
                    member_thread_ids=member_thread_ids,
                )
            )
        result.sort(key=lambda th: (th.group_score, th.score), reverse=True)
        return result[: self.max_prompt_threads]


class ResponseGenerator:
    def __init__(self, base_url: str = "", api_key: str = "", model: str = "local-model", timeout_sec: float = 12.0) -> None:
        self.base_url = normalize_llm_base_url(base_url or os.getenv("LLM_BASE_URL", ""))
        self.api_key = api_key or os.getenv("LLM_API_KEY", "")
        self.model = model or os.getenv("LLM_MODEL", "local-model")
        self.timeout_sec = timeout_sec

    def generate(self, user_input: str, activation: ActivationResult, include_trace: bool = False, trace_limit: int = 10, gate: Optional[ActivationGate] = None) -> str:
        gated = gate.gate(activation) if gate is not None else None
        prompt = build_response_prompt(user_input, activation, include_trace=include_trace, trace_limit=trace_limit, gated=gated)
        print("[LLM Prompt Stats] " + prompt_stats("response_prompt", prompt), file=sys.stderr)

        if self.base_url:
            try:
                print(f"[llm] generating response via {self.base_url} model={self.model}", file=sys.stderr)
                return call_openai_compatible_chat(
                    base_url=self.base_url,
                    api_key=self.api_key,
                    model=self.model,
                    messages=[
                        {
                            "role": "system",
                            "content": (
                                "あなたは日本語で自然に短く返す会話相手です。\n"
                                "Activated Words and Threads are associative memory traces.\n"
                                "They are not exact quoted memories.\n"
                                "Use them as hints for natural recall.\n"
                                "返答は1〜3文。"
                            ),
                        },
                        {"role": "user", "content": prompt},
                    ],
                    temperature=0.7,
                    max_tokens=256,
                    timeout_sec=self.timeout_sec,
                ).strip()
            except Exception as exc:
                print(f"[warn] LLM response generation failed, fallback used: {exc}", file=sys.stderr)
        return fallback_generate_response(user_input, activation)


def build_response_prompt(user_input: str, activation: ActivationResult, include_trace: bool = False, trace_limit: int = 10, gated: Optional[GatedContext] = None) -> str:
    lines: list[str] = []
    lines.append("[Current Input]")
    lines.append(user_input)

    lines.append("")
    lines.append("[Extracted Input Words]")
    for w in activation.input_words:
        lines.append(f"- {w.word} ({w.weight:.2f})")

    if gated is not None:
        lines.append("")
        lines.append("[Gated Recall Context]")
        lines.append(gated.summary)
        lines.append("Only this gated context should be used for the response.")

        lines.append("")
        lines.append("[Gated Thread Groups]")
        for th in gated.threads:
            direct = ", ".join(th.direct_words) if th.direct_words else "-"
            core = " / ".join(th.core_words) if th.core_words else "-"
            support = " / ".join(th.support_words) if th.support_words else "-"
            bonus = f" common_bonus={th.common_bonus:.3f}" if th.common_bonus > 0 else ""
            lines.append(
                f"key={th.canonical_key} occurrence={th.occurrence_count} representative={th.representative_thread_id} "
                f"score={th.score:.3f} group_score={th.group_score:.3f} base={th.base_score:.3f}{bonus} "
                f"eff={th.effective_strength:.3f} direct={direct} core={core} support={support}"
            )

        lines.append("")
        lines.append("[Gated Words]")
        for gw in gated.words:
            lines.append(f"- {gw.word} score={gw.score:.3f} depth={gw.depth} role={gw.role} fatigue={gw.fatigue} reason={gw.reason}")

        if gated.suppressed_words:
            lines.append("")
            lines.append("[Suppressed Words]")
            lines.append("These were activated internally but should not drive the response.")
            for sw in gated.suppressed_words[:10]:
                lines.append(f"- {sw.word} score={sw.score:.3f} depth={sw.depth}")
    else:
        lines.append("")
        lines.append("[Activated Words]")
        for aw in activation.activated_words:
            by = ", ".join(aw.activated_by[:3])
            threads = ", ".join(aw.thread_ids[:5])
            lines.append(f"- {aw.word} score={aw.score:.3f} depth={aw.best_depth} activated_by={by} threads={threads}")

        lines.append("")
        lines.append("[Activated Experience Threads]")
        lines.append("These are not quoted memories. They are experience threads activated by overlapping words.")
        for th in activation.activated_threads:
            words = " / ".join(th.words)
            matched = ", ".join(th.matched_words)
            direct_hint = ""
            if th.common_bonus > 0:
                direct_hint = f" common_bonus={th.common_bonus:.3f}"
            lines.append(
                f"{th.thread_id} score={th.score:.3f} base={th.base_score:.3f}{direct_hint} matched={matched}: {words}"
            )

    if include_trace:
        lines.append("")
        lines.append("[Activation Trace]")
        for tr in activation.traces[:trace_limit]:
            lines.append(f"- d{tr.depth}: {tr.from_type}:{tr.from_id} -> {tr.to_type}:{tr.to_id} score={tr.score:.3f}")
    else:
        lines.append("")
        lines.append("[Activation Trace]")
        lines.append("(omitted from LLM prompt; visible in console log only)")

    lines.append("")
    lines.append("[Instruction]")
    lines.append("励起された単語とthreadは正確な文章記憶ではなく連想の手がかりである。")
    lines.append("複数の入力語が同じthreadを指している場合、そのthreadをより強い手がかりとして扱う。")
    lines.append("Gated Recall Context がある場合は、それを優先し、Suppressed Words は返答の主材料にしない。")
    lines.append("回答では、必要なら『思い浮かんだ』『つながって出てきた』のように自然な想起として表現する。")
    lines.append("断定しすぎず、自然な想起として短く返す。")
    return "\n".join(lines)


def print_activation(result: ActivationResult, trace_limit: int = 80) -> None:
    print("\n[Raw Activation]")
    print("- Input Words")
    for w in result.input_words:
        print(f"  - {w.word} weight={w.weight:.2f}")

    print("- Activated Words")
    for aw in result.activated_words:
        tids = ", ".join(aw.thread_ids[:5])
        by = ", ".join(aw.activated_by[:4]) if aw.activated_by else "-"
        print(f"  - {aw.word} score={aw.score:.4f} depth={aw.best_depth} activated_by={by} threads={tids}")

    print("- Activated Threads")
    for th in result.activated_threads:
        matched = ", ".join(th.matched_words) if th.matched_words else "-"
        by = ", ".join(th.activated_by[:4]) if th.activated_by else "-"
        bonus = f" bonus={th.common_bonus:.4f}" if th.common_bonus > 0 else ""
        print(f"  - {th.thread_id} score={th.score:.4f} base={th.base_score:.4f}{bonus} key={th.canonical_key} same_key_thread_count={th.same_key_thread_count} effective_strength={th.effective_strength:.4f} matched={matched} activated_by={by} date={th.date}: {' / '.join(th.words)}")

    print("\n[Activation Trace]")
    if not result.traces:
        print("- (no trace)")
    for tr in result.traces[:trace_limit]:
        print(f"- d{tr.depth}: {tr.from_type}:{tr.from_id} -> {tr.to_type}:{tr.to_id} score={tr.score:.4f} reason={tr.reason}")


def print_gated_context(gated: GatedContext) -> None:
    print("\n[Recall Selection]")
    print(f"- {gated.summary}")
    print("- selected thread groups")
    if not gated.threads:
        print("  - (none)")
    for th in gated.threads:
        direct = ", ".join(th.direct_words) if th.direct_words else "-"
        core = " / ".join(th.core_words) if th.core_words else "-"
        support = " / ".join(th.support_words) if th.support_words else "-"
        bonus = f" bonus={th.common_bonus:.4f}" if th.common_bonus > 0 else ""
        print(
            f"  - canonical_key={th.canonical_key} occurrence_count={th.occurrence_count} "
            f"representative_thread_id={th.representative_thread_id} member_thread_count={len(th.member_thread_ids)} "
            f"score={th.score:.4f} group_score={th.group_score:.4f}{bonus} effective_strength={th.effective_strength:.4f} "
            f"direct={direct} core={core} support={support} members={', '.join(th.member_thread_ids)}"
        )

    print("- selected words")
    if not gated.words:
        print("  - (none)")
    for gw in gated.words:
        print(f"  - {gw.word} score={gw.score:.4f} depth={gw.depth} role={gw.role} fatigue_prompt={gw.fatigue}")

    print("\n[Conversation Fatigue]")
    if gated.suppressed_words:
        for sw in gated.suppressed_words[:12]:
            print(f"- {sw.word} prompt={sw.fatigue} response=0 suppressed={sw.suppressed_by_fatigue} reason={sw.reason}")
    else:
        print("- (none)")

    print("\n[Working Memory Candidate]")
    print("- promptへ入るThreadGroup")
    for th in gated.threads:
        print(f"  - key={th.canonical_key} occurrence={th.occurrence_count} representative={th.representative_thread_id}")
    print("- promptへ入るWords")
    for gw in gated.words:
        print(f"  - {gw.word}")


def call_openai_compatible_chat(
    base_url: str,
    api_key: str,
    model: str,
    messages: list[dict[str, str]],
    temperature: float,
    max_tokens: int,
    timeout_sec: float,
) -> str:
    url = normalize_llm_base_url(base_url) + "/chat/completions"
    payload = {
        "model": model,
        "messages": messages,
        "temperature": temperature,
        "max_tokens": max_tokens,
        "stream": False,
    }
    headers = {"Content-Type": "application/json"}
    if api_key:
        headers["Authorization"] = f"Bearer {api_key}"

    req = urllib.request.Request(
        url=url,
        data=json.dumps(payload, ensure_ascii=False).encode("utf-8"),
        headers=headers,
        method="POST",
    )

    with open_url_direct(req, timeout=timeout_sec) as resp:
        raw = resp.read().decode("utf-8")

    data = json.loads(raw)
    return data["choices"][0]["message"]["content"]


def check_openai_compatible_health(base_url: str, timeout_sec: float = 3.0) -> tuple[bool, str]:
    base_url = normalize_llm_base_url(base_url)
    if not base_url:
        return False, "base_url is empty"

    root = base_url[:-3] if base_url.endswith("/v1") else base_url
    candidates = [root + "/health", base_url + "/models"]
    last_error = ""
    for url in candidates:
        try:
            req = urllib.request.Request(url=url, method="GET")
            with open_url_direct(req, timeout=timeout_sec) as resp:
                body = resp.read(200).decode("utf-8", errors="replace")
                return True, f"GET {url} -> HTTP {getattr(resp, 'status', 200)} {body[:120]}"
        except Exception as exc:
            last_error = f"GET {url} failed: {exc}"
    return False, last_error


def parse_json_object(text: str) -> dict[str, Any]:
    text = text.strip()
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass
    match = re.search(r"\{.*\}", text, flags=re.DOTALL)
    if not match:
        raise ValueError("No JSON object found in LLM output.")
    return json.loads(match.group(0))


def fallback_extract_words(text: str) -> list[ExtractedWord]:
    text = normalize_text(text)
    protected_terms = [
        *GENERIC_PERSON_TERMS, "チーズケーキ", "コーヒー", "紅茶", "好き",
        "カフェ", "帰り", "食べる", "映画", "ポップコーン",
        "カッターナイフ", "カッター", "怪我", "苦手", "昔",
        "誕生日", "記念日", "猫", "ペット", "ギター",
    ]

    found: list[ExtractedWord] = []
    for term in protected_terms:
        if term in text:
            found.append(ExtractedWord(term, 1.2 if len(term) >= 4 else 1.0))

    if "ケーキ" in text and "チーズケーキ" not in [w.word for w in found]:
        found.append(ExtractedWord("ケーキ", 1.0))
    if "カッター" in text and "カッターナイフ" not in [w.word for w in found]:
        found.append(ExtractedWord("カッターナイフ", 0.9))

    chunks = re.findall(r"[A-Za-z0-9]+|[ぁ-んァ-ン一-龥ー]{2,}", text)
    stop = {"です", "ます", "だった", "って", "これ", "それ", "今日", "明日", "昨日", "する", "した", "ある", "いる", "もの", "なもの"}
    for ch in chunks:
        ch = normalize_word(ch)
        if not ch or ch in stop:
            continue
        if len(ch) >= 8 and re.search(r"[はがをにへでとてもやの]", ch):
            continue
        if any(ch in term and ch != term for term in protected_terms):
            continue
        found.append(ExtractedWord(ch, 0.8))

    return dedupe_extracted_words(found)


def dedupe_extracted_words(words: list[ExtractedWord]) -> list[ExtractedWord]:
    d: dict[str, float] = {}
    for item in words:
        word = normalize_word(item.word)
        if not word:
            continue
        d[word] = max(d.get(word, 0.0), clamp(item.weight, 0.1, 2.0))
    return [ExtractedWord(w, weight) for w, weight in sorted(d.items(), key=lambda kv: kv[1], reverse=True)]


def match_known_words(input_word: str, known_words: list[str]) -> list[tuple[str, float]]:
    input_word = normalize_word(input_word)
    if not input_word:
        return []

    result: list[tuple[str, float]] = []
    for known in known_words:
        if input_word == known:
            result.append((known, 1.0))
        elif input_word in known or known in input_word:
            short_len = max(min(len(input_word), len(known)), 1)
            long_len = max(max(len(input_word), len(known)), 1)
            sim = 0.72 + 0.20 * (short_len / long_len)
            result.append((known, clamp(sim, 0.55, 0.92)))
        elif loose_katakana_match(input_word, known):
            result.append((known, 0.72))

    result.sort(key=lambda x: x[1], reverse=True)
    return result[:12]


def loose_katakana_match(a: str, b: str) -> bool:
    a2 = a.replace("ー", "")
    b2 = b.replace("ー", "")
    return len(a2) >= 3 and len(b2) >= 3 and (a2 in b2 or b2 in a2)


def fallback_generate_response(user_input: str, activation: ActivationResult) -> str:
    top = [w.word for w in activation.activated_words[:6]]
    if not top:
        return "まだうまく思い出せないけど、その話もう少し聞かせて。"
    if "チーズケーキ" in top and "コーヒー" in top:
        return "チーズケーキとコーヒーが強く出てきてるよ。ユーザーの好きなものとして、その二つがつながってる感じがする。"
    if "チーズケーキ" in top:
        return "チーズケーキが出てきたよ。ユーザーが好きって話とつながってる気がする。"
    if "カッターナイフ" in top or "カッター" in top:
        return "カッターや怪我、苦手って単語が反応してる。少し気をつけた方がよさそう。"
    return "今反応してるのは、" + "、".join(top[:4]) + " あたりかな。"


def add_activated_by(target: dict[str, list[str]], key: str, value: str) -> None:
    target.setdefault(key, [])
    if value not in target[key]:
        target[key].append(value)


def merge_unique(values: list[str]) -> list[str]:
    merged: list[str] = []
    for value in values:
        if value and value not in merged:
            merged.append(value)
    return merged


def add_word_activation(
    word_scores: dict[str, float],
    word_best_depth: dict[str, int],
    word_threads: dict[str, set[str]],
    word_activated_by: dict[str, list[str]],
    word: str,
    thread_ids: list[str],
    score: float,
    depth: int,
    activated_by: str,
) -> None:
    word_scores[word] = word_scores.get(word, 0.0) + score
    word_best_depth[word] = min(word_best_depth.get(word, 99), depth)
    word_threads.setdefault(word, set()).update(thread_ids)
    add_activated_by(word_activated_by, word, activated_by)


def estimate_prompt_tokens_rough(text: str) -> int:
    ascii_chars = sum(1 for c in text if ord(c) < 128)
    non_ascii_chars = len(text) - ascii_chars
    return int((ascii_chars / 4.0) + (non_ascii_chars / 1.6))


def prompt_stats(label: str, text: str) -> str:
    return f"{label}: chars={len(text)}, lines={text.count(chr(10)) + 1 if text else 0}, rough_tokens={estimate_prompt_tokens_rough(text)}"


def prompt_stats_dict(text: str) -> dict[str, int]:
    return {
        "chars": len(text),
        "lines": text.count("\n") + 1 if text else 0,
        "rough_tokens": estimate_prompt_tokens_rough(text),
    }


def normalize_thread_strength_mode(value: str) -> str:
    # Weighted-mode comparison experiments are closed.
    # Trace-based Recall Engine v1 uses count as the fixed storage mode.
    return FIXED_THREAD_STRENGTH_MODE


def make_canonical_key(words) -> str:
    normalized = []
    for w in words:
        word = normalize_word(str(w))
        if word:
            normalized.append(word)
    return "|".join(sorted(set(normalized)))


def normalize_text(text: str) -> str:
    return text.strip().replace("　", " ")


def normalize_word(word: str) -> str:
    word = normalize_text(word)
    return word.strip(" \t\r\n。、,.!?！？「」『』（）()[]【】")


def clamp(v: float, lo: float, hi: float) -> float:
    return max(lo, min(hi, v))


def now_iso() -> str:
    return dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds")


def days_between_iso(start: str, end: str) -> float:
    try:
        s = dt.datetime.fromisoformat(start)
        e = dt.datetime.fromisoformat(end)
        return max((e - s).total_seconds() / 86400.0, 0.0)
    except Exception:
        return 0.0


def row_to_word_node(row: sqlite3.Row) -> WordNode:
    return WordNode(
        word_id=row["word_id"],
        word=row["word"],
        strength=float(row["strength"]),
        weight=float(row["weight"]),
        seen_count=int(row["seen_count"]),
        first_seen=row["first_seen"],
        last_seen=row["last_seen"],
    )


def row_to_word_thread_link(row: sqlite3.Row) -> WordThreadLink:
    return WordThreadLink(
        word_id=row["word_id"],
        word=row["word"],
        thread_id=row["thread_id"],
        weight_in_thread=float(row["weight_in_thread"]),
        added_at=row["added_at"],
    )



def build_gate(args: argparse.Namespace, store: Optional[ThreadedConceptMemoryStore] = None) -> Optional[ActivationGate]:
    if getattr(args, "disable_gate", False):
        return None
    return ActivationGate(
        max_prompt_threads=args.gate_max_threads,
        max_core_words_per_thread=args.gate_max_core_words,
        max_prompt_words=args.gate_max_words,
        min_thread_score=args.gate_min_thread_score,
        min_word_score=args.gate_min_word_score,
        support_ratio=args.gate_support_ratio,
        store=store,
        fatigue_recent_turns=args.fatigue_recent_turns,
        fatigue_threshold=args.fatigue_threshold,
    )


def build_components(args: argparse.Namespace) -> tuple[ThreadedConceptMemoryStore, WordExtractor, ActivationEngine, ResponseGenerator]:
    store = ThreadedConceptMemoryStore(args.db)
    extractor_model = getattr(args, "extractor_model", "") or args.model
    response_model = getattr(args, "response_model", "") or args.model
    extractor = WordExtractor(args.base_url, args.api_key, extractor_model, args.timeout)
    engine = ActivationEngine(store, args.half_life_days, args.max_depth, args.common_bonus, args.mutual_amplification, args.thread_strength_mode)
    generator = ResponseGenerator(args.base_url, args.api_key, response_model, args.timeout)
    return store, extractor, engine, generator


def cmd_add(args: argparse.Namespace) -> int:
    store, extractor, _, _ = build_components(args)
    try:
        words = extractor.extract(args.text)
        thread_id = store.create_thread(words, source_text=args.text, thread_strength_mode=args.thread_strength_mode)
        print(f"saved: {thread_id}")
        print("words:", " / ".join(f"{w.word}({w.weight:.2f})" for w in words))
        return 0
    finally:
        store.close()


def cmd_ask(args: argparse.Namespace) -> int:
    store, extractor, engine, generator = build_components(args)
    try:
        words = extractor.extract(args.text)
        result = engine.activate(words, args.top_words, args.top_threads)
        print(f"\n[Storage Mode]\n{args.thread_strength_mode}")
        print_activation(result, trace_limit=args.trace_limit)
        gate = build_gate(args, store)
        gated = gate.gate(result) if gate is not None else None
        if gate is not None:
            print_gated_context(gated)
        if not args.no_reinforce:
            store.reinforce_seen(result.activated_words)
        response_text = ""
        if not args.no_response:
            print("\n[Response]")
            response_text = generator.generate(args.text, result, args.response_include_trace, args.response_trace_limit, gate=gate)
            print(response_text)
        else:
            print("\n[Response]")
            print("(skipped)")
            print("reason=no_response_mode")
        if gated is not None:
            turn_no = store.record_exposures(gated, exposure_type="prompt")
            if response_text:
                store.record_exposures(gated, turn_no=turn_no, exposure_type="response", response_text=response_text)
        return 0
    finally:
        store.close()


def cmd_threads(args: argparse.Namespace) -> int:
    store = ThreadedConceptMemoryStore(args.db)
    try:
        for th in store.list_threads(args.limit):
            print(f"{th.thread_id} {th.date} key={th.canonical_key} strength={th.strength:.2f} seen={th.seen_count}: {' / '.join(th.words)}")
            if args.show_source:
                print(f"  source(debug only): {th.source_text}")
        return 0
    finally:
        store.close()


def cmd_words(args: argparse.Namespace) -> int:
    store = ThreadedConceptMemoryStore(args.db)
    try:
        for node in store.list_words(args.limit):
            links = store.get_links_for_word(node.word_id)
            tids = ", ".join(l.thread_id for l in links[:8])
            print(f"{node.word} seen={node.seen_count} strength={node.strength:.2f} weight={node.weight:.2f} threads={tids}")
        return 0
    finally:
        store.close()


def cmd_seed_tests(args: argparse.Namespace) -> int:
    store, extractor, engine, generator = build_components(args)
    try:
        print(f"[Storage Mode] {args.thread_strength_mode}")
        seed_fixture = Path(args.seed_tests_file)
        fixture_turns = load_eval_conversation(seed_fixture)
        seeds = [str(item["user"]) for item in fixture_turns if item["mode"] == "learn"]
        tests = [str(item["user"]) for item in fixture_turns if item["mode"] in {"ask", "ask_no_response"}]

        for s in seeds:
            words = extractor.extract(s)
            thread_id = store.create_thread(words, source_text=s, thread_strength_mode=args.thread_strength_mode)
            print(f"seed saved: {thread_id}: {s}")
            print("  words:", " / ".join(w.word for w in words))

        for t in tests:
            print("\n" + "=" * 60)
            print("[Test Input]", t)
            words = extractor.extract(t)
            result = engine.activate(words, args.top_words, args.top_threads)
            print(f"\n[Storage Mode]\n{args.thread_strength_mode}")
            print_activation(result, trace_limit=args.trace_limit)
            gate = build_gate(args, store)
            gated = gate.gate(result) if gate is not None else None
            if gate is not None:
                print_gated_context(gated)
            response_text = ""
            if args.seed_generate_response:
                print("\n[Response]")
                response_text = generator.generate(t, result, args.response_include_trace, args.response_trace_limit, gate=gate)
                print(response_text)
            if gated is not None:
                turn_no = store.record_exposures(gated, exposure_type="prompt")
                if response_text:
                    store.record_exposures(gated, turn_no=turn_no, exposure_type="response", response_text=response_text)
            else:
                print("\n[Response]")
                print("(skipped; use --seed-generate-response to test LLM response generation)")
        return 0
    finally:
        store.close()


def cmd_chat(args: argparse.Namespace) -> int:
    store, extractor, engine, generator = build_components(args)
    try:
        print("Threaded Concept Memory Probe v0.9")
        print(f"LLM: {'enabled ' + normalize_llm_base_url(args.base_url) if normalize_llm_base_url(args.base_url) else 'disabled; fallback mode'}")
        print("HTTP proxy: bypassed for local/direct calls")
        print("Commands: /exit, /threads, /words, /add <text>, /ask <text>")
        print("Default: input is treated as /ask, then stored as a new thread.")
        while True:
            try:
                text = input("\n> ").strip()
            except EOFError:
                print()
                break

            if not text:
                continue
            if text in {"/exit", "exit", "quit", "/quit"}:
                break
            if text == "/threads":
                for th in store.list_threads(20):
                    print(f"{th.thread_id} {th.date} key={th.canonical_key} strength={th.strength:.2f} seen={th.seen_count}: {' / '.join(th.words)}")
                continue
            if text == "/words":
                for node in store.list_words(50):
                    links = store.get_links_for_word(node.word_id)
                    print(f"{node.word} seen={node.seen_count} threads={len(links)}")
                continue

            mode = "ask_then_add"
            if text.startswith("/add "):
                mode = "add"
                text = text[5:].strip()
            elif text.startswith("/ask "):
                mode = "ask"
                text = text[5:].strip()

            words = extractor.extract(text)

            if mode in {"ask", "ask_then_add"}:
                result = engine.activate(words, args.top_words, args.top_threads)
                print(f"\n[Storage Mode]\n{args.thread_strength_mode}")
                print_activation(result, trace_limit=args.trace_limit)
                gate = build_gate(args, store)
                gated = gate.gate(result) if gate is not None else None
                if gate is not None:
                    print_gated_context(gated)
                store.reinforce_seen(result.activated_words)
                print("\n[Response]")
                response_text = generator.generate(text, result, args.response_include_trace, args.response_trace_limit, gate=gate)
                print(response_text)
                if gated is not None:
                    turn_no = store.record_exposures(gated, exposure_type="prompt")
                    store.record_exposures(gated, turn_no=turn_no, exposure_type="response", response_text=response_text)

            if mode in {"add", "ask_then_add"}:
                thread_id = store.create_thread(words, source_text=text, thread_strength_mode=args.thread_strength_mode)
                print(f"\n[saved] {thread_id}: " + " / ".join(w.word for w in words))

        return 0
    finally:
        store.close()


def cmd_config(args: argparse.Namespace) -> int:
    base_url = normalize_llm_base_url(args.base_url or args.chat_base_url or os.getenv("LLM_BASE_URL", ""))
    print("[LLM Config]")
    print(f"base_url: {base_url or '(not set; fallback mode)'}")
    print(f"model: {args.model}")
    print(f"extractor_model: {getattr(args, 'extractor_model', '') or args.model}")
    print(f"response_model: {getattr(args, 'response_model', '') or args.model}")
    print(f"api_key: {'set' if (args.api_key or os.getenv('LLM_API_KEY')) else '(not set)'}")
    print(f"NO_PROXY: {os.environ.get('NO_PROXY', '')}")
    print("proxy_mode: disabled for this script's HTTP calls")
    if not base_url:
        return 0
    ok, detail = check_openai_compatible_health(base_url, timeout_sec=min(args.timeout, 5.0))
    print("health:", "ok" if ok else "failed")
    print("detail:", detail)
    if args.generate_test:
        try:
            content = call_openai_compatible_chat(
                base_url=base_url,
                api_key=args.api_key,
                model=args.model,
                messages=[
                    {"role": "system", "content": "Return only JSON. No explanation."},
                    {"role": "user", "content": "{\"ok\":true}"},
                ],
                temperature=0.0,
                max_tokens=16,
                timeout_sec=args.timeout,
            )
            print("generation: ok")
            print("sample:", content.strip()[:200])
        except Exception as exc:
            print("generation: failed")
            print("error:", exc)
    return 0


def cmd_prompt_preview(args: argparse.Namespace) -> int:
    store, extractor, engine, _ = build_components(args)
    try:
        words = extractor.extract(args.text)
        result = engine.activate(words, args.top_words, args.top_threads)
        gate = build_gate(args, store)
        gated = gate.gate(result) if gate is not None else None
        prompt_without_trace = build_response_prompt(args.text, result, include_trace=False, gated=gated)
        prompt_with_trace = build_response_prompt(args.text, result, include_trace=True, trace_limit=args.response_trace_limit, gated=gated)
        print_activation(result, trace_limit=args.trace_limit)
        if gated is not None:
            print_gated_context(gated)
        print("\n[Prompt Size]")
        print(prompt_stats("without_trace", prompt_without_trace))
        print(prompt_stats(f"with_trace_limit_{args.response_trace_limit}", prompt_with_trace))
        if args.show_prompt:
            print("\n[Prompt Without Trace]")
            print(prompt_without_trace)
            print("\n[Prompt With Trace]")
            print(prompt_with_trace)
        return 0
    finally:
        store.close()


def cmd_eval(args: argparse.Namespace) -> int:
    store, extractor, engine, generator = build_components(args)
    events: list[dict[str, Any]] = []
    metrics_rows: list[dict[str, Any]] = []
    report_lines: list[str] = []
    conversation_path = Path(args.conversation_file)

    try:
        turns = load_eval_conversation(conversation_path)
        report_lines.extend(
            [
                "# Threaded Concept Memory Probe Evaluation",
                "",
                f"- conversation_file: `{conversation_path}`",
                f"- db: `{args.db}`",
                f"- storage_mode: `{FIXED_THREAD_STRENGTH_MODE}`",
                "- weighted_mode: excluded from current evaluation scope",
                f"- response_generation: `{eval_response_generation_label(args)}`",
                "",
                "| turn | mode | response_skipped | expected_hit_count | unexpected_hit_count | precision_like | recall_noise_count | fatigue_suppressed_count | response_used_expected_count | response_used_unexpected_count | prompt_tokens_rough | prompt_thread_group_count | response_used_group_count | recall_efficiency | prompt_word_count |",
                "|---:|---|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|",
            ]
        )

        for item in turns:
            event = run_eval_turn(item, args, store, extractor, engine, generator)
            events.append(event)
            if event["mode"] in {"ask", "ask_no_response"}:
                metrics = event["metrics"]
                metrics_rows.append(flatten_eval_metrics(event))
                report_lines.append(
                    "| {turn} | {mode} | {response_skipped} | {expected_hit_count} | {unexpected_hit_count} | {recall_precision_like:.3f} | "
                    "{recall_noise_count} | {fatigue_suppressed_count} | {response_used_expected_count} | "
                    "{response_used_unexpected_count} | {prompt_tokens_rough} | {prompt_thread_group_count} | {response_used_group_count} | "
                    "{recall_efficiency:.3f} | {prompt_word_count} |".format(**metrics)
                )

        write_jsonl(Path(args.events_jsonl), events)
        write_metrics_csv(Path(args.metrics_csv), metrics_rows)
        report_lines.extend(build_eval_report_summary(metrics_rows))
        write_text(Path(args.report_md), "\n".join(report_lines) + "\n")

        print(f"[Eval] events_jsonl={args.events_jsonl}")
        print(f"[Eval] metrics_csv={args.metrics_csv}")
        print(f"[Eval] report_md={args.report_md}")
        return 0
    finally:
        store.close()


def load_eval_conversation(path: Path) -> list[dict[str, Any]]:
    turns: list[dict[str, Any]] = []
    with path.open("r", encoding="utf-8") as f:
        for line_no, line in enumerate(f, start=1):
            line = line.strip()
            if not line:
                continue
            try:
                item = json.loads(line)
            except json.JSONDecodeError as exc:
                raise ValueError(f"{path}:{line_no}: invalid JSONL: {exc}") from exc
            mode = item.get("mode")
            if mode not in {"learn", "ask", "ask_no_response"}:
                raise ValueError(f"{path}:{line_no}: mode must be learn, ask, or ask_no_response")
            if "user" not in item:
                raise ValueError(f"{path}:{line_no}: missing user")
            turns.append(item)
    return turns


def eval_response_generation_label(args: argparse.Namespace) -> str:
    if getattr(args, "no_response", False):
        return "skipped by --no-response"
    return "enabled" if normalize_llm_base_url(args.base_url) else "fallback/no remote LLM"


def run_eval_turn(
    item: dict[str, Any],
    args: argparse.Namespace,
    store: ThreadedConceptMemoryStore,
    extractor: WordExtractor,
    engine: ActivationEngine,
    generator: ResponseGenerator,
) -> dict[str, Any]:
    turn = int(item.get("turn", 0))
    user_text = str(item["user"])
    mode = str(item["mode"])
    expected_words = [normalize_word(str(w)) for w in item.get("expected_words", []) if normalize_word(str(w))]
    unexpected_words = [normalize_word(str(w)) for w in item.get("unexpected_words", []) if normalize_word(str(w))]
    words = extractor.extract(user_text)

    if mode == "learn":
        thread_id = store.create_thread(words, source_text=user_text, thread_strength_mode=args.thread_strength_mode)
        return {
            "turn": turn,
            "mode": mode,
            "user": user_text,
            "saved_thread_id": thread_id,
            "input_words": [w.word for w in words],
            "response_skipped": False,
        }

    activation = engine.activate(words, args.top_words, args.top_threads)
    gate = build_gate(args, store)
    gated = gate.gate(activation) if gate is not None else GatedContext([], [], [], "Gate disabled.")
    prompt = build_response_prompt(user_text, activation, include_trace=args.response_include_trace, trace_limit=args.response_trace_limit, gated=gated)
    response_text = ""
    response_skipped = mode == "ask_no_response" or getattr(args, "no_response", False)
    if mode == "ask" and not response_skipped:
        response_text = generator.generate(user_text, activation, args.response_include_trace, args.response_trace_limit, gate=gate)

    if not args.no_reinforce:
        store.reinforce_seen(activation.activated_words)

    turn_no = store.record_exposures(gated, exposure_type="prompt")
    if response_text:
        store.record_exposures(gated, turn_no=turn_no, exposure_type="response", response_text=response_text)

    metrics = evaluate_recall_turn(
        turn=turn,
        mode=mode,
        expected_words=expected_words,
        unexpected_words=unexpected_words,
        activation=activation,
        gated=gated,
        prompt=prompt,
        response_text=response_text,
        response_skipped=response_skipped,
    )
    return {
        "turn": turn,
        "mode": mode,
        "user": user_text,
        "expected_words": expected_words,
        "unexpected_words": unexpected_words,
        "input_words": [w.word for w in activation.input_words],
        "activated_words": [aw.word for aw in activation.activated_words],
        "gated_words": [gw.word for gw in gated.words],
        "selected_thread_groups": [gated_thread_group_to_dict(th) for th in gated.threads],
        "suppressed_words": [gated_word_to_dict(sw) for sw in gated.suppressed_words],
        "prompt_stats": prompt_stats_dict(prompt),
        "response_text": response_text,
        "response_skipped": response_skipped,
        "metrics": metrics,
    }


def evaluate_recall_turn(
    turn: int,
    mode: str,
    expected_words: list[str],
    unexpected_words: list[str],
    activation: ActivationResult,
    gated: GatedContext,
    prompt: str,
    response_text: str,
    response_skipped: bool = False,
) -> dict[str, Any]:
    gated_word_set = {gw.word for gw in gated.words}
    working_memory_group_count = len(gated.threads)
    working_memory_word_count = len(gated_word_set)
    response_used_groups = [th.canonical_key for th in gated.threads if response_uses_thread_group(response_text, th)]
    response_expected = [w for w in expected_words if w and w in response_text]
    response_unexpected = [w for w in unexpected_words if w and w in response_text]
    expected_hits = [w for w in expected_words if w in gated_word_set or (w and w in response_text)]
    unexpected_hits = [w for w in unexpected_words if w in gated_word_set or (w and w in response_text)]
    prompt_only = [w for w in gated_word_set if w and w not in response_text]
    denom = len(expected_hits) + len(unexpected_hits)
    precision_like = (len(expected_hits) / denom) if denom else (1.0 if not unexpected_hits else 0.0)
    return {
        "turn": turn,
        "mode": mode,
        "input_words": [w.word for w in activation.input_words],
        "activated_words": [aw.word for aw in activation.activated_words],
        "gated_words": sorted(gated_word_set),
        "selected_thread_groups": [th.canonical_key for th in gated.threads],
        "suppressed_words": [sw.word for sw in gated.suppressed_words],
        "prompt_tokens_rough": prompt_stats_dict(prompt)["rough_tokens"],
        "prompt_thread_group_count": working_memory_group_count,
        "prompt_word_count": working_memory_word_count,
        "response_text": response_text,
        "response_skipped": response_skipped,
        "expected_hit_count": len(expected_hits),
        "unexpected_hit_count": len(unexpected_hits),
        "recall_precision_like": precision_like,
        "recall_noise_count": len(unexpected_hits),
        "fatigue_suppressed_count": sum(1 for sw in gated.suppressed_words if sw.suppressed_by_fatigue),
        "response_used_expected_count": len(response_expected),
        "response_used_unexpected_count": len(response_unexpected),
        "working_memory_group_count": working_memory_group_count,
        "response_used_group_count": len(response_used_groups),
        "recall_efficiency": (len(response_used_groups) / working_memory_group_count) if working_memory_group_count else 0.0,
        "working_memory_word_count": working_memory_word_count,
        "response_used_groups": response_used_groups,
        "expected_hits": expected_hits,
        "unexpected_hits": unexpected_hits,
        "prompt_only": sorted(prompt_only),
    }


def response_uses_thread_group(response_text: str, group: GatedThreadGroup) -> bool:
    if not response_text:
        return False
    candidate_words = merge_unique(group.core_words + group.direct_words + group.support_words + group.words)
    return any(word and word in response_text for word in candidate_words)


def gated_thread_group_to_dict(th: GatedThreadGroup) -> dict[str, Any]:
    return {
        "canonical_key": th.canonical_key,
        "representative_thread_id": th.representative_thread_id,
        "occurrence_count": th.occurrence_count,
        "score": th.score,
        "group_score": th.group_score,
        "base_score": th.base_score,
        "common_bonus": th.common_bonus,
        "effective_strength": th.effective_strength,
        "words": th.words,
        "direct_words": th.direct_words,
        "core_words": th.core_words,
        "support_words": th.support_words,
        "suppressed_words": th.suppressed_words,
        "member_thread_ids": th.member_thread_ids,
    }


def gated_word_to_dict(word: GatedWord) -> dict[str, Any]:
    return {
        "word": word.word,
        "score": word.score,
        "depth": word.depth,
        "role": word.role,
        "reason": word.reason,
        "fatigue_prompt": word.fatigue,
        "suppressed_by_fatigue": word.suppressed_by_fatigue,
    }


def flatten_eval_metrics(event: dict[str, Any]) -> dict[str, Any]:
    metrics = event["metrics"]
    return {
        "turn": metrics["turn"],
        "mode": metrics["mode"],
        "input_words": json.dumps(metrics["input_words"], ensure_ascii=False),
        "activated_words": json.dumps(metrics["activated_words"], ensure_ascii=False),
        "gated_words": json.dumps(metrics["gated_words"], ensure_ascii=False),
        "selected_thread_groups": json.dumps(metrics["selected_thread_groups"], ensure_ascii=False),
        "suppressed_words": json.dumps(metrics["suppressed_words"], ensure_ascii=False),
        "prompt_tokens_rough": metrics["prompt_tokens_rough"],
        "prompt_thread_group_count": metrics["prompt_thread_group_count"],
        "prompt_word_count": metrics["prompt_word_count"],
        "response_text": metrics["response_text"],
        "response_skipped": str(metrics["response_skipped"]).lower(),
        "expected_hit_count": metrics["expected_hit_count"],
        "unexpected_hit_count": metrics["unexpected_hit_count"],
        "recall_precision_like": f"{metrics['recall_precision_like']:.6f}",
        "recall_noise_count": metrics["recall_noise_count"],
        "fatigue_suppressed_count": metrics["fatigue_suppressed_count"],
        "response_used_expected_count": metrics["response_used_expected_count"],
        "response_used_unexpected_count": metrics["response_used_unexpected_count"],
        "working_memory_group_count": metrics["working_memory_group_count"],
        "response_used_group_count": metrics["response_used_group_count"],
        "recall_efficiency": f"{metrics['recall_efficiency']:.6f}",
        "working_memory_word_count": metrics["working_memory_word_count"],
        "response_used_groups": json.dumps(metrics["response_used_groups"], ensure_ascii=False),
        "prompt_only": json.dumps(metrics["prompt_only"], ensure_ascii=False),
    }


def write_jsonl(path: Path, rows: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        for row in rows:
            f.write(json.dumps(row, ensure_ascii=False) + "\n")


def write_metrics_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = [
        "turn",
        "mode",
        "input_words",
        "activated_words",
        "gated_words",
        "selected_thread_groups",
        "suppressed_words",
        "prompt_tokens_rough",
        "prompt_thread_group_count",
        "prompt_word_count",
        "response_text",
        "response_skipped",
        "expected_hit_count",
        "unexpected_hit_count",
        "recall_precision_like",
        "recall_noise_count",
        "fatigue_suppressed_count",
        "response_used_expected_count",
        "response_used_unexpected_count",
        "working_memory_group_count",
        "response_used_group_count",
        "recall_efficiency",
        "working_memory_word_count",
        "response_used_groups",
        "prompt_only",
    ]
    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def build_eval_report_summary(rows: list[dict[str, Any]]) -> list[str]:
    if not rows:
        return ["", "## Summary", "", "- ask turns: 0"]
    expected = sum(int(r["expected_hit_count"]) for r in rows)
    unexpected = sum(int(r["unexpected_hit_count"]) for r in rows)
    fatigue = sum(int(r["fatigue_suppressed_count"]) for r in rows)
    avg_precision = sum(float(r["recall_precision_like"]) for r in rows) / len(rows)
    avg_efficiency = sum(float(r["recall_efficiency"]) for r in rows) / len(rows)
    wm_groups = sum(int(r["working_memory_group_count"]) for r in rows)
    response_groups = sum(int(r["response_used_group_count"]) for r in rows)
    wm_words = sum(int(r["working_memory_word_count"]) for r in rows)
    response_skipped = sum(1 for r in rows if str(r["response_skipped"]).lower() == "true")
    return [
        "",
        "## Summary",
        "",
        f"- ask turns: {len(rows)}",
        f"- Response skipped turns: {response_skipped}",
        f"- expected_hit_count_total: {expected}",
        f"- unexpected_hit_count_total: {unexpected}",
        f"- fatigue_suppressed_count_total: {fatigue}",
        f"- average_recall_precision_like: {avg_precision:.3f}",
        f"- working_memory_group_count_total: {wm_groups}",
        f"- response_used_group_count_total: {response_groups}",
        f"- average_recall_efficiency: {avg_efficiency:.3f}",
        f"- working_memory_word_count_total: {wm_words}",
    ]


def make_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Threaded Concept Memory Probe v0.9")
    parser.add_argument("--db", default=DEFAULT_DB_PATH)
    parser.add_argument("--base-url", default=os.getenv("LLM_BASE_URL", ""))
    parser.add_argument("--chat-base-url", default="")
    parser.add_argument("--api-key", default=os.getenv("LLM_API_KEY", ""))
    parser.add_argument("--model", default=os.getenv("LLM_MODEL", "local-model"))
    parser.add_argument("--extractor-model", default=os.getenv("LLM_EXTRACTOR_MODEL", ""), help="Optional model override for word extraction; defaults to --model.")
    parser.add_argument("--response-model", default=os.getenv("LLM_RESPONSE_MODEL", ""), help="Optional model override for response generation; defaults to --model.")
    parser.add_argument("--timeout", type=float, default=12.0)
    parser.add_argument("--half-life-days", type=float, default=DEFAULT_HALF_LIFE_DAYS)
    parser.add_argument("--max-depth", type=int, default=DEFAULT_MAX_DEPTH)
    parser.add_argument("--top-words", type=int, default=20)
    parser.add_argument("--top-threads", type=int, default=8)
    parser.add_argument("--trace-limit", type=int, default=80)
    parser.add_argument("--common-bonus", type=float, default=0.45, help="Bonus multiplier for threads supported by multiple direct/input words.")
    parser.add_argument("--mutual-amplification", type=float, default=0.12, help="Small word boost from strong co-activated threads.")
    parser.add_argument("--response-include-trace", action="store_true")
    parser.add_argument("--response-trace-limit", type=int, default=10)
    parser.add_argument("--thread-strength-mode", choices=["weighted", "count"], default="count", help="Deprecated: count is fixed for Trace-based Recall Engine v1; weighted is coerced to count.")
    parser.add_argument("--fatigue-recent-turns", type=int, default=10)
    parser.add_argument("--fatigue-threshold", type=int, default=3)
    parser.add_argument("--disable-gate", action="store_true", help="Disable v0.8 Activation Gate and send raw activation summary.")
    parser.add_argument("--gate-max-threads", type=int, default=4)
    parser.add_argument("--gate-max-core-words", type=int, default=5)
    parser.add_argument("--gate-max-words", type=int, default=12)
    parser.add_argument("--gate-min-thread-score", type=float, default=0.05)
    parser.add_argument("--gate-min-word-score", type=float, default=0.05)
    parser.add_argument("--gate-support-ratio", type=float, default=0.18)

    sub = parser.add_subparsers(dest="command", required=True)

    p_add = sub.add_parser("add")
    p_add.add_argument("text")
    p_add.set_defaults(func=cmd_add)

    p_ask = sub.add_parser("ask")
    p_ask.add_argument("text")
    p_ask.add_argument("--no-response", action="store_true")
    p_ask.add_argument("--no-reinforce", action="store_true")
    p_ask.set_defaults(func=cmd_ask)

    p_threads = sub.add_parser("threads")
    p_threads.add_argument("--limit", type=int, default=20)
    p_threads.add_argument("--show-source", action="store_true")
    p_threads.set_defaults(func=cmd_threads)

    p_words = sub.add_parser("words")
    p_words.add_argument("--limit", type=int, default=100)
    p_words.set_defaults(func=cmd_words)

    p_seed = sub.add_parser("seed-tests")
    p_seed.add_argument(
        "--seed-tests-file",
        default=str(DEFAULT_SEED_TESTS_FILE),
        help="JSONL fixture used by seed-tests; defaults to eval_conversations/seed_tests_public.jsonl.",
    )
    p_seed.add_argument("--seed-generate-response", action="store_true")
    p_seed.set_defaults(func=cmd_seed_tests)

    p_chat = sub.add_parser("chat")
    p_chat.set_defaults(func=cmd_chat)

    p_config = sub.add_parser("config")
    p_config.add_argument("--generate-test", action="store_true")
    p_config.set_defaults(func=cmd_config)

    p_preview = sub.add_parser("prompt-preview")
    p_preview.add_argument("text")
    p_preview.add_argument("--show-prompt", action="store_true")
    p_preview.set_defaults(func=cmd_prompt_preview)

    p_eval = sub.add_parser("eval")
    p_eval.add_argument("--conversation-file", required=True)
    p_eval.add_argument("--db", default=DEFAULT_DB_PATH)
    p_eval.add_argument("--base-url", default=os.getenv("LLM_BASE_URL", ""))
    p_eval.add_argument("--chat-base-url", default="")
    p_eval.add_argument("--api-key", default=os.getenv("LLM_API_KEY", ""))
    p_eval.add_argument("--model", default=os.getenv("LLM_MODEL", "local-model"))
    p_eval.add_argument("--extractor-model", default=os.getenv("LLM_EXTRACTOR_MODEL", ""))
    p_eval.add_argument("--response-model", default=os.getenv("LLM_RESPONSE_MODEL", ""))
    p_eval.add_argument("--timeout", type=float, default=12.0)
    p_eval.add_argument("--half-life-days", type=float, default=DEFAULT_HALF_LIFE_DAYS)
    p_eval.add_argument("--max-depth", type=int, default=DEFAULT_MAX_DEPTH)
    p_eval.add_argument("--top-words", type=int, default=20)
    p_eval.add_argument("--top-threads", type=int, default=8)
    p_eval.add_argument("--thread-strength-mode", choices=["weighted", "count"], default="count", help="Deprecated: eval benchmarks are count-only; weighted is coerced to count.")
    p_eval.add_argument("--common-bonus", type=float, default=0.45)
    p_eval.add_argument("--mutual-amplification", type=float, default=0.12)
    p_eval.add_argument("--response-include-trace", action="store_true")
    p_eval.add_argument("--response-trace-limit", type=int, default=10)
    p_eval.add_argument("--fatigue-recent-turns", type=int, default=10)
    p_eval.add_argument("--fatigue-threshold", type=int, default=3)
    p_eval.add_argument("--disable-gate", action="store_true")
    p_eval.add_argument("--gate-max-threads", type=int, default=4)
    p_eval.add_argument("--gate-max-core-words", type=int, default=5)
    p_eval.add_argument("--gate-max-words", type=int, default=12)
    p_eval.add_argument("--gate-min-thread-score", type=float, default=0.05)
    p_eval.add_argument("--gate-min-word-score", type=float, default=0.05)
    p_eval.add_argument("--gate-support-ratio", type=float, default=0.18)
    p_eval.add_argument("--report-md", required=True)
    p_eval.add_argument("--events-jsonl", required=True)
    p_eval.add_argument("--metrics-csv", required=True)
    p_eval.add_argument("--no-reinforce", action="store_true")
    p_eval.add_argument("--no-response", action="store_true")
    p_eval.set_defaults(func=cmd_eval)

    return parser


def main(argv: Optional[list[str]] = None) -> int:
    parser = make_parser()
    args = parser.parse_args(argv)

    if getattr(args, "chat_base_url", ""):
        args.base_url = args.chat_base_url
    args.base_url = normalize_llm_base_url(args.base_url)
    requested_mode = getattr(args, "thread_strength_mode", FIXED_THREAD_STRENGTH_MODE)
    args.thread_strength_mode = normalize_thread_strength_mode(requested_mode)
    if requested_mode != args.thread_strength_mode:
        print(
            f"[warn] thread-strength-mode={requested_mode} is no longer part of evaluation/storage policy; using count.",
            file=sys.stderr,
        )

    return int(args.func(args))


if __name__ == "__main__":
    raise SystemExit(main())
